### ISSUE TITLE
Merge ref_vk into main.

### ISSUE THREAD

**Issue by Rykita** [yquake2/yquake2#1019] opened 2023-06-02 07:09 UTC
As the title suggests, I've been left to wonder why is the Vulkan renderer a separate repo? It's an outlier in this regard as GL1.4, GLES, GL3.2, Software are all in this repo. Is it due to the experimental nature of the VK renderer?

**Comment by 0lvin** [comment] 2023-06-02 18:26
We are always appreciate contributions to ref_vk and when code will have same level of code quality and features set as gl3, it could be merged back to main repository or remove experimental flag at least.

**Comment by Yamagi** [comment] 2023-06-05 17:40
The biggest problem is that Vulkans requirements are incompatible with Quake IIs architecture. For example Vulkan can abort a frame after each and every API call, Quake II only has very limited handling for aborted frames. While Vulkan may work well enough for the average use case, there are a lot of corner cases caused by these architectural limitations we weren't able to solve with the time we could invest into it. Since GL3 is is arguably a better renderer feature wise we have given up on Vulkan and moved it into an external repository for user who can't run GL3 but Vulkan.

**Closed by Yamagi** 2023-06-05 17:40 UTC
