### ISSUE TITLE
Hornet doesn't spawn in Big Gun level

### ISSUE THREAD

**Issue by skitt** [yquake2/yquake2#295] opened 2018-05-07 15:12 UTC
Hi,

I've been playing my way through Quake II again, and I've come across an annoying issue: the hornet doesn't spawn in the Big Gun level, which means I'm stuck...

This is with version 7.20, on Debian 9. My save file is available on https://sk2.org/save6.zip

Regards,

Stephen

**Comment by Yamagi** [comment] 2018-05-07 17:56
Hi,
the Big Gun was always a problematic level with a number of bugs but this one is new. I've never heard of it before or encountered it myself. In your savegame the hornet is clearly missing and it's probably save to assume that it didn't spawn in at level now. I have no idea who that could happen. I tried to reproduce it but even after 25 level loads it didn't happen again. Looks like it'l take some time to fix this.

The problem is that Quake II doesn't have a way to spawn enemys through the console. The best chance to continue your game is to enable `noclip` and fly through the door triggered by the hornet. Disable `noclip`, push the button, fly again through the door and finish the level.

And thank you for the savegame, it'll be a big help in debugging this!

Regards,
Yamagi

**Comment by skitt** [comment] 2018-05-09 12:31
I do indeed still have the previous savegame, see https://sk2.org/save5.zip

I hadn't realised that all the monsters spawn on level load, that's very useful information, thanks! Reloading the level from the previous one spawns the hornet in most cases. I thought this was purely “action-time” behaviour, but since it isn’t it might be relevant that up until this issue occurred, I was playing on version 6.00, and I upgraded to 7.20 to check whether the bug occurred there too (not realising that it was set in stone in the savegame). So save5 and save6 were saved with version 6.00, not 7.20; I initially only reloaded save6 in 7.20 to check the issue there. Reloading save5 has so far worked every time.

**Comment by DanielGibson** [comment] 2018-05-09 13:37
Hmm whatever caused the bug, we probably fixed it since 6.00 then. I'll close this bug then (in case it's still reproducible with 7.20 after all it can still be reopened).

Thanks for reporting anyway, I hope you have fun with 7.20 and maybe enjoy the new features (like the slightly prettier GL3 renderer) ;-)

In case you encounter more problems, please open new bugreports for them!

**Closed by DanielGibson** 2018-05-09 13:37 UTC

**Comment by skitt** [comment] 2018-05-09 18:13
Thanks for the prompt feedback (and for the engine too, version 7 is indeed very nice!), it is *very* much appreciated.
