### ISSUE TITLE
[Bug] Map "Pumping Station 2" (waste3) "target_secret" missing (fix)

### ISSUE THREAD

**Issue by KPThug** [yquake2/yquake2#773] opened 2021-12-08 03:12 UTC
Solution:
In g_spawn.c -> "SpawnEntities" function

After:
if (!Q_stricmp(level.mapname, "command") && !Q_stricmp(ent->classname, "trigger_once") && !Q_stricmp(ent->model, "*27"))
   ent->spawnflags &= ~SPAWNFLAG_NOT_HARD;

Add:
if (!Q_stricmp(level.mapname, "waste3") && !Q_stricmp(ent->classname, "func_door") && !Q_stricmp(ent->model, "*12"))
   ent->target = "t117";

PD: No idea how to add it to the .ent files.

Regards, Gustavo.

**Comment by BjossiAlfreds** [comment] 2021-12-08 17:56
This was already fixed in the baseq2 dll, in g_func.c. Though of course an ent file is always better than a code hack, as it would work independent of the game dll being used.

**Comment by BjossiAlfreds** [comment] 2021-12-08 20:46
@Yamagi If you want I can commit a waste3.ent that addresses this and bad player start from console, and remove the code hacks.

I also spotted 2 gunners that have the spawnflags 1024 (not hard/nightmare). I feel like this is a bug and was intended to be 768 (not easy + not medium). I haven't change this but thought I'd mention it. Thoughts?

**Comment by Yamagi** [comment] 2021-12-11 12:10
> If you want I can commit a waste3.ent that addresses this and bad player start from console, and remove the code hacks.

That would be nice.

> I also spotted 2 gunners that have the spawnflags 1024 (not hard/nightmare). I feel like this is a bug and was intended to be 768 (not easy + not medium). I haven't change this but thought I'd mention it. Thoughts?

You could fix this in the entity files. Player who use the files will get the gunners on easy and medium. Purists playing without the entity files will keep the Vanilla behavior.

**Comment by Yamagi** [comment] 2021-12-11 18:08
I've merged the pull request.

**Closed by Yamagi** 2021-12-11 18:08 UTC
