### ISSUE TITLE
5.24 client mouse turn problem when play multiplayer games

### ISSUE THREAD

**Issue by ppsspp-gamer** [yquake2/yquake2#64] opened 2015-03-25 19:18 UTC
When I play a multiplayer game with 5.24 client, I can only turn left and right about 90 degrees with mouse. I don't have this problem with 5.23 client.

steps to reproduce this bug:
(1) run qsb.exe (Quake 2 server browser)
(2) select a server to connect
(3) press fire button to join the game

![qsb](https://cloud.githubusercontent.com/assets/8726272/6833189/24c67548-d366-11e4-921d-97cf21e4db41.png)

But if I start a dedicate server with yquake2 supported game.dll then join my own server, I don't have this problem either.

**Comment by DanielGibson** [comment] 2015-03-25 19:27
Without looking at the code or trying to reproduce, this sounds like for 
some reason relative mouse mode doesn't work like it should, i.e. when 
the (hidden) mouse pointer reached the window border it doesn't go on.
Could be both a bug on our side or with SDL.

(Or maybe something completely different, this was just a wild guess)

**Comment by Jarvik7** [comment] 2015-03-26 00:39
This bug has hit me a few times in the single player too, but I can't reproduce it consistently.

**Comment by Yamagi** [comment] 2015-03-26 08:16
This f***ing problem again... We had that at least two time before:
  * The first time on Linux / Unix systems SDL2 didn't enable relative mouse mode when xinput was build without multicursor support. We added the work around in src/backends/sdl/input.c line 371.
  * Later wie hit the problem again on Windows, because security software (I'm pretty sure that is was Comodo Antivirus) was blocking access to raw mouse events. That time a better work around was added to SDL. It's part of SDL 2.0.3 which is the version used by our Windows builds.

From a quick glance the work around in Quake II still looks good and should avoid hitting the window borders in all situations.  It smells like I've broken that fragile, crappy code somewhere while refactoring the keyboard input to respect the local keyboard layout. I'll have a look in the next few days.

**Comment by Yamagi** [comment] 2015-03-26 18:41
Okay, after some pondering is see the possibility that the input initialization code is never executed. I need to verify that. Can you please reproduce the problem and send us the log files? They're in C:\Users\$yourname\Documents\stdout.txt and stderr.txt. The path may differ between versions and locales. 

Thank you :)

**Comment by ppsspp-gamer** [comment] 2015-03-26 22:10
@Yamagi here is the log you want.
http://www.mediafire.com/download/h267xi8wm2cg76o/YamagiQ2_log.zip

I tested with 5.24 client download from official web site.

**Comment by DanielGibson** [comment] 2015-03-27 17:19
Ok, I think I can reproduce that bug, even on Linux.

From your log I see that when connecting to the server video (and sound) is reinitialized, probably the server sends a vid_restart (whyever it should do that..).  
Anyway, I binded vid_restart to a key and if I press that key the window is recreated and afterwards the mouse isn't grabbed anymore and I can't turn very far (only until the mouse leaves the window).

I'm optimistic that we can come up with a fix for this :-)

**Comment by ppsspp-gamer** [comment] 2015-03-27 18:08
@DanielGibson glad to hear that you can easily reproduce this bug.

**Comment by DanielGibson** [comment] 2015-03-27 18:36
I think I've fixed it.  
If you send me an E-Mail to metalcaedes@gmail.com I'll send you updated binaries to test :)

**Comment by ppsspp-gamer** [comment] 2015-03-27 20:46
Good job, just tested with your client and this bug is fixed.

**Comment by DanielGibson** [comment] 2015-03-27 22:51
Great!  
The fix is in the https://github.com/yquake2/yquake2/tree/fix-input-grab branch, btw

I don't know if yamagi will merge it to master like this or if he wants further improvements, but at least it seems to work.

**Comment by Yamagi** [comment] 2015-03-29 17:01
I've merged it just a few minutes ago. Thank you for this bug report. :)

**Closed by Yamagi** 2015-03-29 17:01 UTC
