### ISSUE TITLE
Change projectile lighting to yellow

### ISSUE THREAD

**Issue by xboxownzuall** [yquake2/yquake2#640] opened 2020-12-31 19:46 UTC
This source port claims the graphics are unchanged, but they are the projectile lighting from rocket is changed from yellow to orange. How do i change it back to the yellow lighting found in 3.20 retail? Also the particle effects on rockets are pixelated if you switch renderer to open gl 1.4 that's one thing i seriously do not like and wish would stick true to original game.That would be a good menu option to have to change from orange or to yellow tbh.Also whats up with the machine guns projectile lighting being broken with v sync off?  3.20 or 3.24 or even vulkan quake 2 or aprq dont have these problems only witnessed this in q2pro or yamagi or r1q2 where the muzzle flash is just a yellow line across the screen and  muzzle flashes too slow, i appreciate the work done, but this stuff needs to be sorted out also the console is broken on newest yamagi release also my ~` key aint working.

**Comment by Yamagi** [comment] 2021-01-02 16:32
> This source port claims the graphics are unchanged, but they are the projectile lighting from rocket is changed from yellow to orange.

Quake II never had one defined look for the GL renderer, because it uses the OpenGL 1.4 fixed function pipeline were some operations are driver dependent. For example how overlaying images like the base texture, base lightmap and the dynamic lightmap generated to draw the dlights are merged together. And the Vanilla Quake II GL renderer supported palleted textures, Yamagi Quake II remove that because no newer GPU has support for the required GL extensions anyways. If you want one defined look, regardless of the GPU driver in use select the GL3 or Vulkan renderer.

> Also the particle effects on rockets are pixelated if you switch renderer to open gl 1.4 that's one thing i seriously do not like and wish would stick true to original game.

GL1 uses the `GL_SMOOTH` attribute for nice looking particles. The attribute is ignored by several newer GPU drivers, Mesa3D for Radeons and Intel GPUs is one example. Nothing we do there.

> also the console is broken on newest yamagi release also my ~` key aint working.

The console is on shift-esc. the game tries to figure out what key is the 'key bellow esc'  and binds the console to that one, too. Depending on the keyboard layout it may work or not.

**Comment by xboxownzuall** [comment] 2021-01-07 00:12
I dont see a vukan renderer option in the newest yamagi menu either how would I run that? Vulkan quake 2 made by another guy  https://github.com/kondrak/vkQuake2  that renders the rockets lighting correctly, yamagi doesnt tho.

Pretty sure the color of the rockets lighting is the modders choice, and it's not dependant on which gpu or driver you are running lol.

**Comment by Yamagi** [comment] 2021-01-10 09:41
Mkay, I see what you mean. In Vanilla Q2 the rocket trail dynamic lights are colored  (1,1,0). In YQ2 they are (1, 0.25, 0). That change came from r1q2 and was merged in 45202621a14b6a1d6eba27d8b61604cee320d910, the third commit I've made. In the current code it's here: https://github.com/yquake2/yquake2/blob/master/src/client/cl_entities.c#L448 The rocket explosion is somewhere else. In r1q2 the differend color is hidden behind `cl_original_dlights`, which is the default. I think I'll add something like that to YQ2.

> I dont see a vukan renderer option in the newest yamagi menu either how would I run that?

It's under Video -> Renderer. The 4th option, after Software and before Custom.

**Comment by Yamagi** [comment] 2021-01-10 09:42
I forgot to add: You can select all renderers by cvar. `vid_renderer` with either `gl1`, `gl3`, `soft` or `vk`.

**Comment by DanielGibson** [comment] 2021-01-10 11:44
Keep in mind that the latest release (7.45) doesn't include the vulkan renderer, you need to build the latest git code (or use the latest windows testbuild from https://deponie.yamagi.org/quake2/windows/testbuilds/)

**Comment by Yamagi** [comment] 2021-01-10 18:12
> Pretty sure the color of the rockets lighting is the modders choice, and it's not dependant on which gpu or driver you are running lol.

The lightning is set by the client, modders can't change it. But  what's rendered on screen is highly dependent on the renderer and with the OpenGL 1.4 the major part of the renderer is the fixed function pipeline implementation of the driver. With my Radeon and Mesa3D I find it hard to notice, that the colors are different. Especially if gamma is high. On my Geforce it's easy to see.

Anyways, I've implemented `cl_r1q2_lightstyle`, set it to `0` and you'll get the Vanilla Quake II colors for rockets and hyperblaster projectiles. A new test build is here: https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-20210110-462a0dd.zip

**Comment by xboxownzuall** [comment] 2021-01-10 23:14
its almost perfect the rocket is correct now , but the hyperblasters color
is white like software rendered version instead of yellow it's yellow when
it hits the wall but when projectiles in the air it's white and that's
supposed to be yellow also.

**Comment by Yamagi** [comment] 2021-01-11 06:42
Mkay, I changed the hyperblaster to matcn the 3.21 sources: https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-20210111-023a012.zip

**Comment by xboxownzuall** [comment] 2021-01-11 12:13
Yes everything appears to be correct now, i appreciate it alot thanks.One
last question will you plz keep this as a command option in all future
releases/official? cl_r1q2_lightstyle.

**Comment by Yamagi** [comment] 2021-01-11 15:56
No worries. :) The changes are in the *master* branch and will be part of all releases from now on. The next will be 8.00.

**Comment by xboxownzuall** [comment] 2021-01-11 18:52
Hey one last suggestion, could u make it so if u set cl_r1q2_lightstyle to
3 it would make the open gl 3.2 colored/orange/smooth lighting
edges available in vulkan renderer? if that's possible that would be nice,
if it's not possible thats all good no big deal.

**Comment by xboxownzuall** [comment] 2021-01-11 19:13
ok these are my last suggestions, make it so yamagi transitions from
windowed mode to fullscreen perfectly , everytime i press alt+enter it just
goes back to fullscreen doesnt work properly, fix the minor graphical bugs
in the vulkan renderer seams showing at times and add 3rd option to
cl_r1q2_lightstyle 3 to allow smooth projectile 3.2 open gl lighting in
vulkan.

**Comment by xboxownzuall** [comment] 2021-01-13 02:41
i dont wanna come across as ungrateful because im sure as hell not, i just
now noticed the flyer enemy his lighting is now white like software mode
instead of yellow like it's supposed to be.

**Comment by xboxownzuall** [comment] 2021-01-13 04:36
Nm scratch that last bug i was using older build woops the color of the
lighting is fine, but yes it would be nice to have the open gl 3.2 smoothed
edge lighting avalible in vulkan also and yes vulkan does have some
graphical glitches as with kondraks vulkan quake 2 source port around the
seams of stuff and i wish i could alt+enter for windowed/fullscreen  mode
like 3.24 quake 2 or kmquake 2 or kondraks vulkan quake 2 please see if you
can get this stuff sorted out.You are doing the gamer gods work lol.

**Comment by xboxownzuall** [comment] 2021-01-13 04:40
what i mean by smoothed edge lighting is with open gl 3.2 you dont see the
blocky edges when a rocket hits a wall it's smoothed over and
cl_r1q2_lightstyle 0 works perfectly with a yellow lighting like that, but
yes the blended edge lighting would be nice in vulkan renderer mode also
not just gl3.

Nm scratch that last bug i was using older build woops the color of the
lighting is fine, but yes it would be nice to have the open gl 3.2 smoothed
edge lighting avalible in vulkan also and yes vulkan does have some
graphical glitches as with kondraks vulkan quake 2 source port around the
seams of stuff and i wish i could alt+enter for windowed/fullscreen  mode
like 3.24 quake 2 or kmquake 2 or kondraks vulkan quake 2 please see if you
can get this stuff sorted out.You are doing the gamer gods work lol.

**Comment by Yamagi** [comment] 2021-01-13 10:08
> i wish i could alt+enter for windowed/fullscreen  mode like 3.24 quake 2 or kmquake 2 or kondraks vulkan quake 2

The problem here is SDL2 - https://libsdl.org/ - that we're using as platform abstraction library. SDL recreates the windows when the render configuration (resolution, fullscreen mode, etc.) is changed. And that requires a renderer restart in YQ2. Therefor dynamic resolution changes like q2pro supports them aren't possible.

When alt-enter is pressed, `vid_fullscreen` is set to `1`.  That's the "Keep Resolution" fullscreen option in the video menu. When the current resolution is smaller than the display native resolution the background is painted black and the game windows is placed somewhere. Where exactly is dependent on the operating system, the GPU driver and the graphics API. For me it's placed at the bottom left for GL3 and upper left for Vulkan.  
This is one these things that can't be done right because everybody has other preferences. No matter if we keep the display resolution, change the display resolution or keep the display resolution and change the games resolution, someone will always problem. Keeping the display and game resolution was choosen because it is the safest choice, especially in multi monitor setups under Linux.

>  it would be nice to have the open gl 3.2 smoothed edge lighting avalible in vulkan.

This is something that somebody with more Vulkan knowledge than me must look into. Maybe @0lvin or @rg3. I'm not quite sure how we solved this in GL3. As far as I remeber GL1 (and likely the Vulkan renderer) used some kind of tiles for the dynamic lightning. The dynamic lightmap for each surface is divided into a grid of tiles, for each tile a light value is calculated and the dynamic lightmap is rendered over the static lightmap. Or something like that. Since the tiles are rather big, dynamic lights are rendered in blocks. GL3 calculates the dynamic light through a shader on per a per pixel base.

> vulkan does have some graphical glitches

Do you have screenshots for these? Fixes for the particle problems and the skybox boundries are already in flight and will land soon.

**Comment by rg3** [comment] 2021-01-14 19:06
I'd love to help improve that but I barely know the engine and I'm not exactly an expert using Vulkan for practical visual effects :disappointed:. If nobody takes the task and it remains open for a long time, I may explore it, but it will take me a long time on top of that.

**Comment by Yamagi** [comment] 2021-01-17 10:34
That's total okay. :) I've opened a new issue fur the lighting stuff as #651, to make it better visible. Maybe someone stops up. And if not Vulkan still looks good, GL3 just looks a little bit better (and still misses the underwater effect).

**Comment by xboxownzuall** [comment] 2021-01-20 00:07
ya when you get blown up close to walls u see graphical glitches also i
meant, there's some other graphical glitches here and there besides the one
on inner chamber.

**Comment by xboxownzuall** [comment] 2021-02-10 18:53
See the graphical bugs?  also if you noclip you will see graphical bugs
when you go outside the level it doesnt glitch grided white glitches in
open gl 1.4 or 3.2 gl like that.

it's around the seams of stuff

**Comment by DanielGibson** [comment] 2021-02-10 19:17
could you post screenshots?

but note that we don't care what the game looks like when noclipping through the void, only in regular gameplay

**Comment by xboxownzuall** [comment] 2021-02-11 13:52
the graphical glitches that appear when you noclip are leaking through the
seams of the game and making artifacts appear inside the levels memory
leaks some crap like that maybe.

Here's are two screenshots scroll down

https://imgur.com/a/noKON4K

**Comment by DanielGibson** [comment] 2021-02-11 14:27
Looks like the glitches you get with OpenGL when setting `r_clear 1`.
I suggest that the vulkan renderer should also use `r_clear` (and not clear by default)

**Comment by Yamagi** [comment] 2021-02-11 16:03
The clearing in done in `QVk_BeginRenderpass()`.

**Comment by xboxownzuall** [comment] 2021-02-11 16:07
what do you mean?  is that a command?

**Comment by DanielGibson** [comment] 2021-02-11 16:13
no, it's a function in the code and it's a hint where to look for the people working on the vulkan renderer so they can fix it

**Comment by xboxownzuall** [comment] 2021-02-11 19:48
Did you see the graphical bugs in the pictures? i circled the graphical
artifacts/glitches for u just incase u missed em.

https://imgur.com/a/CjCrXoz

**Comment by rg3** [comment] 2021-02-13 23:35
I'm unable to reproduce those exact glitches with the latest version of my more-vulkan-fixes branch from PR #658.

I've uploaded a video to show that, at least in my system (Linux, NVIDIA proprietary drivers), the glitches I see in the Vulkan renderer are similar to the ones in the OpenGL 3.2 renderer. What I see in the screenshots above matches what perhaps could be seen if you don't clear an image with undefined layout with some Vulkan implementations (hardware+drivers). This type of glitch should no longer be visible after the skybox fixes were merged, which tackle more or less the same problem.

Please see:

https://drive.google.com/file/d/1V3p4PQuJ7DtNheF-_YvpAriCbEuR8wW4/view?usp=sharing

**Comment by xboxownzuall** [comment] 2021-03-01 09:21
Do you have link so i can test wth latest build with vulkan if im seeing glitches other ones i seen?

**Comment by rg3** [comment] 2021-03-01 18:44
@xboxownzuall if you mean Windows builds, PR #658 was merged a few days ago and there are updated builds you can find in https://github.com/yquake2/yquake2/issues/505#issuecomment-787489929, thanks!

**Comment by Yamagi** [comment] 2021-03-10 10:12
Another build is here: https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-20210310-2a18f02.zip

**Closed** 2021-03-20 15:24 UTC
Labels: vulkan
