### ISSUE TITLE
Script issue in Torture Chambers

### ISSUE THREAD

**Issue by some0nebad** [yquake2/yquake2#495] opened 2019-12-29 15:10 UTC
Well, I think this is a script issue.

In this room, after death of this marine, a key should fall out. But in the latest version (7.42), it does not appear if you kill him by yourself. Key will appear only after the strogg presses the button and you do not interfere. Version 7.30 does not have this issue.

Windows 7 x64
[![yq2](https://user-images.githubusercontent.com/52467651/71558518-220fb000-2a5d-11ea-93fc-e32bcbc6b4c7.jpg)
](url)

**Comment by some0nebad** [comment] 2019-12-29 15:30
And you can press a button and wait for his death, and key will appear. But if you shoot him it will not

**Comment by Yamagi** [comment] 2020-01-01 12:29
Hi,
thank you for the report. I'll look into it, but it'll take a few days.

**Comment by DanielGibson** [comment] 2020-01-01 22:19
@BjossiAlfreds: We haven't investigated this, but as most recent changes to the game code have been yours, it might make sense if you look at it (if you have some time)?

**Comment by BjossiAlfreds** [comment] 2020-01-01 22:53
Sure, I'll help you guys out and look into it as well.

**Comment by BjossiAlfreds** [comment] 2020-01-01 23:34
I looked into the jail4.bsp entity string. The misc_insane guy has a target t130, which means upon death he should fire target t130 and trigger all entities with targetname t130, including a target_spawner which spawns key_pass.

I have tested in-game and I can confirm there is something wrong and targets aren't being fired like they should. I'll take a closer look at the code and try to see what is causing this, there is a strong probability one of my many bugfixes broke this...

**Comment by DanielGibson** [comment] 2020-01-02 00:14
Thanks for debugging this! :)

I guess we can try to find another struct member and try to make double-sure it's not otherwise used by the insanes - otherwise we'll have to live with the pain sounds getting cut off.

**Comment by BjossiAlfreds** [comment] 2020-01-02 00:28
I went shopping at local.h and I have a candidate - fly_sound_debounce_time. I did a full reference check and it is only used in g_trigger by trigger_push. I would of course add a comment to make sure we don't forget about this hack.

**Comment by BjossiAlfreds** [comment] 2020-01-02 11:55
I have made PRs for yq2, rogue and xatrix that fix this bug. Since it can be game-breaking it may be a good idea to update the currently released 7.42 binaries.

**Comment by Yamagi** [comment] 2020-01-05 09:11
I just merged the PRs. I'll build a new set of Windows binaries tonight or tomorrow.

**Closed by Yamagi** 2020-01-05 09:11 UTC
