### ISSUE TITLE
GL3 Shadow Bug

### ISSUE THREAD

**Issue by shoober420** [yquake2/yquake2#194] opened 2017-05-10 01:27 UTC
I found a bug with the GL3 shadows. When a shadow casts on a destructable wall or floor, it will not render the shadow and instead allow you to see through the texture. Heres the video.

https://www.youtube.com/watch?v=Pm-WO-VKhko

**Comment by Yamagi** [comment] 2017-05-13 15:16
This is another driver dependent bug. I was to reproduce it on:
* Intel Ivy Bridge with Mesa3D
* Radeon R7 370 on Mesa3D
* Radeon R7 370 on Windows

And unable on:
* Geforce 750 TI on FreeBSD with the Blob
* Intel on OS X

The problem may be caused by rendering the objects in the wrong order, maybe shadows first and entity models last.

**Comment by shoober420** [comment] 2017-05-13 17:35
That's odd, I'm using the NVIDIA blob on Linux version 381.22, and it occurs. I'll have to post about it on the NVIDIA forums then. Thank you.

**Comment by Yamagi** [comment] 2017-05-13 19:39
This is not a driver problem. Just that different GPUs show different behavior in undefined situations. Quake II draws the the world, after that each entity and it's shadow. In base1 the barrel and it's shadow are drawn first, the breakable plane above the hole later. Mesa3D and at least some versions of Nvidias driver create the shadow by combining the look into the hole with some shading, giving the impression that the breakable plane is missing. In my understanding this is the expected behavior. Intel on OS X and my version of Nvidias driver (or even the GPU family) are somewhat more intelligent and update the shadows texture as soon as the breakable plane is drawn.

A possible fix would be to change the drawing order. Draw the world, all entities and the shadows last. But I'm afraid that such a fix would require a bigger amount of refactoring. And there may be a negative performance impact.

**Comment by shoober420** [comment] 2017-05-13 23:27
Sorry for the misunderstanding. My card is a GeForce 760, so out cards aren't too far apart.

**Comment by DanielGibson** [comment] 2017-05-15 10:42
This should be fixed via #198 (code also available at https://github.com/DanielGibson/yquake2/tree/gl3-shadows-last), please test it before it gets merged

**Comment by shoober420** [comment] 2017-05-15 14:31
This a probably a dumb question, but how do I build a package that uses the pull requests? I just do git pulls from master, I've never did a git pull from master+pull requests.

**Comment by DanielGibson** [comment] 2017-05-15 15:03
I think it's easiest if you clone and build my repo, like
```sh
git clone https://github.com/DanielGibson/yquake2.git yq2-dg
cd yq2-dg
# switch to this branch:
git checkout gl3-shadows-last
# compile the code (as usual)
make -j4
# now test the fresh binaries in release/ as usual
```

**Closed** 2017-05-16 06:58 UTC

**Comment by shoober420** [comment] 2017-05-16 20:08
I'm sorry I didn't get around to this sooner. I was busy. This does fix the issue though. Thank you guys
