### ISSUE TITLE
DM maps not listed when starting a server in GUI

### ISSUE THREAD

**Issue by GumbyDeath** [yquake2/yquake2#217] opened 2017-07-26 15:50 UTC
Hello

Installed the 7.01 release for windows last night and noticed the DM maps were not listed in the GUI when starting a server. They are the first option with the original quake2.exe client.

**Comment by DanielGibson** [comment] 2017-07-27 07:29
Uhh.. well.. you know how we tell you in the installation instructions 
to delete baseq2/maps.lst?
Turns out that you should rather keep it :-/

(The maps listed there are from baseq2/maps.lst, and as that file is 
missing in the installation directory, it falls back to the one from 
pak0.pak, which does not include the deathmatch maps that were added to 
the game in a patch after release)

Please keep the bug open, we'll close it once we've adjusted the 
installation instructions.

It'd be great if you could test if not deleting baseq2/maps.lst actually 
works for you though :)

Cheers,
Daniel

**Comment by GumbyDeath** [comment] 2017-07-27 07:43
Oddly enough I did not delete maps.lst it is in my baseq directory and has
the dm maps in it.

**Comment by Yamagi** [comment] 2017-08-02 09:09
Okay, the problem is:

1. At first Quake II looks for `$HOME/.yq2/$mod/maps.lst` (Unix) or `%Documents%\YamagiQ2\$mod\maps.lst`. If it finds the file everything's okay.
2. After that - if the file is not found - FS_FOpenFile() is called. It goes through the global search path, the first match serves. Paks are searched before directories, in case of the main game `baseq2/pak0.pak/maps.lst` matches. But that's the older release version that doesn't contain the deathmatch maps. `baseq2/maps.lst` would be the correct choice.

I'll need to ponder how to fix that.

**Comment by GumbyDeath** [comment] 2017-08-02 14:34
I guess my assumption was that Yamagi was a drop in replacement for the
original quake2.exe program and that it would behave the same. Based on
that I assumed it would read the same config files so I could switch back
and forth between the clients. My 2 cents would be to have it look for and
use files in the .yq2 or YamagiQ2 directories first and if they are not
there read all of the default files like the original Quake 2.

Would that be the same reason the model files in the baseq2 directory are
not being read either? It is reading the pak0.pak file only?

**Comment by Yamagi** [comment] 2017-08-02 18:10
I've just commited a hack that solves the issue and restores the original behavior. At least as far as it's possible, the original client had a much simpler searchpath.

**Closed by Yamagi** 2017-08-02 18:10 UTC

**Comment by GumbyDeath** [comment] 2017-08-02 20:47
Awesome thank you! Is there a schedule for releases or just when enough
changes pile up?

**Comment by Yamagi** [comment] 2017-08-03 05:33
No, there's no schedule. But I think that we'll do the next release 7.02 at beginning of september.
