### ISSUE TITLE
Feature request: Support more architectures

### ISSUE THREAD

**Issue by Danfun64** [yquake2/yquake2#138] opened 2016-06-07 20:23 UTC
ATM This source port adds amd64 support to the existing i386 support. While those two architectures may be among the most common, they aren't the only ones. ARM, MIPS, and PowerPC support would also be nice.

One of Quake 2's biggest flaws is its lack of portability. That, combined with Debian using yquake2 as its quake 2 code base (apparently it used to use vanilla ported to all the aforementioned platforms. Not anymore though...)

**Comment by Yamagi** [comment] 2016-06-07 20:43
YQ2 was tested on common 32 Bit, 64 bit LP and LLP, little endian and big endian. Tested architectures include IA64, ARMv7 and PPC64. At one point it even ran on SPARC64 with it's hard alignement requirements. I don't see why there should be any bigger problems on ARMv8, MIPS or even RISC-V. Of course there may be some small compiler errors, but they shouldn't be a big problem. And you'll need to add the platform defines, otherwise Yamagi Quake II will default to "unknown"...

**Comment by DanielGibson** [comment] 2016-06-07 21:22
I don't know why debian only supplies packages fir i386 and amd64, maybe open a bug report there and ask them? As Yamagi said, this port should work on all kinds of architectures, so if there are any problems, they should be minor and the debian package maintainer could probably resolve them and we'd integrate the patches needed, if any.

**Comment by Danfun64** [comment] 2016-06-07 23:06
Similar question. Do I need to do anything special to port mods to use the multi-architecture codebase yquake2 uses?

**Comment by Yamagi** [comment] 2016-06-08 05:26
Okay, somewhat more comprehensive:

* As said YQ2 should run on most or even all CPU architectures. There may be some small problems with compile errors, but they should be easy to fix. For a new CPU architecture a CPUSTRING define should be added to src/common/header/common.h. It's used in several outputs like backtraces, the 'version' cvar, etc. Additionally both baseq2 and the addons need an OS define in savegame/savegame.c. This one is embedded into the savegame and prevents loading of incompatible savegames from other architectures. Both defines are optional, without them the generic string 'unknown' is used.
* More problematic as YQ2 itself is SDL. For example some years ago the old SDL 1.2 was buggy and unstable on SPARC64. I don't know in what shape SDL 2.0 is on more exotic architectures like MIPS, RISC-V or SuperH / J-Core.
* The often somewhat limited GPUs embedded into common single board computer SoC may lack the old fixed function OpenGL 1.2 pipeline and fall back to slow software rendering. In fact, some day the renderer will need to be rewritten in modern OpenGL for YQ2 staying compatible with low-end hardware.

**Comment by smcv** [comment] 2016-06-08 07:22
> I don't know why debian only supplies packages fir i386 and amd64, maybe open a bug report there and ask them?

We supply packages for the architectures that yquake2's Makefile says it aims to support:

```
# Refuse all other platforms as a firewall against PEBKAC
# (You'll need some #ifdef for your unsupported  plattform!)
ifeq ($(findstring $(ARCH), i386 x86_64 sparc64 ia64),)
$(error arch $(ARCH) is currently not supported)
endif
```

ia64 is no longer in Debian and sparc64 is not yet a release architecture, so we provide binaries for every release architecture that yquake2 says it supports. Of course, we could patch this check out, but that would seem rude - I don't want people sending bug reports upstream for architectures you are specifically not willing to deal with.

If yquake2 is in fact broadly portable, it would probably make sense to do something similar to this ioquake3 commit, changing the assumption to "works on any architecture":

https://github.com/ioquake/ioq3/commit/2a71948f21fe588dbce9b29409283e9c912ef8e7

(Quake 3's `ARCH` and `ARCH_STRING` are essentially the same thing as your `ARCH` and `CPUSTRING`, as far as I can see.)

I happen to have an old 32-bit PowerPC laptop, which if it works would complete the matrix of (32, 64)-bit × (little, big)-endian. If I prepare a pull request that changes the policy from "supported architectures only" to "any Linux architecture is probably OK", and it works on PowerPC without PowerPC-specific changes, would you be willing to remove the architecture whitelist?

> More problematic as YQ2 itself is SDL. For example some years ago the old SDL 1.2 was buggy and unstable on SPARC64. I don't know in what shape SDL 2.0 is on more exotic architectures like MIPS, RISC-V or SuperH / J-Core.

This is really an issue for architecture porters and the SDL maintainers, not for you. I would hope that anyone using architectures that far outside the mainstream understands how porting works.

> The often somewhat limited GPUs embedded into common single board computer SoC may lack the old fixed function OpenGL 1.2 pipeline and fall back to slow software rendering.

I think this is a separate issue; a modernized OpenGL driver (like ioquake3's opengl2) is orthogonal to whether yquake2 compiles on a given CPU family at all.

**Comment by Yamagi** [comment] 2016-06-08 18:00
I've just commited an approach similar to ioQuake3s into the issue138 branch.  Just as I said in the commit message it'll break existing savegames on several architectures due to changed defines. But I guess that's acceptable since it avoids some other hacks.

**Comment by Danfun64** [comment] 2016-06-08 22:35
Will the new savegame format be architecture agnostic? Since old savegames are architecture specific, are old demos also architecture specific?

**Comment by Yamagi** [comment] 2016-06-09 05:29
Quake II savegames are operating system and architecture depended by design. We fixed them enough to be compiler and even build agnostic, but more can't done. :( My change breaks them since the operating system and platform identifier changes and Quake II can't detect them as compatible. After some thoughts about it I think we can bump the savegame version:

* Old savegames are checked for compatibility by using the old identifiers.
* New savegames by using the new identifiers.

I'll come up with another patch.

**Comment by smcv** [comment] 2016-06-09 07:52
I would recommend reverting <https://github.com/yquake2/yquake2/commit/ade81d54724ed10a3d9ac25d22562aa528288450>. There's no real guarantee that `uname -m` won't change over time on any particular platform; worst case, a distribution build could be incompatible for savegames depending what machine it was built on (if anyone still has a working i586).

Normalizing `^arm.*` to `arm` is probably also a good idea: that's the other bit of normalization done in ioquake3's Makefile. A 32-bit ARM machine will typically report something like `armv5tel` in its `uname -m`, but they're all fundamentally the same ABI, in the same way that `i386` and `i686` share an ABI. 64-bit ARM is a different ABI, but it's also a different `uname -m`, `aarch64`, specifically to avoid matching `^arm.*`.

**Comment by Yamagi** [comment] 2016-06-09 17:49
I just pushed another set of changes:

* Compatibility with old savegames is back.
* amd64, arm and i386 are normalized again.

**Comment by Yamagi** [comment] 2016-06-11 07:55
I've merged this into master and all 3 addons.

**Closed by Yamagi** 2016-06-11 07:55 UTC
