### ISSUE TITLE
Binding Mousewheel to Jump Does Not Work

### ISSUE THREAD

**Issue by rwzd** [yquake2/yquake2#1105] opened 2024-05-10 00:35 UTC
**Version**: 8.30 from [here](https://deponie.yamagi.org/quake2/windows/quake2-8.30.zip)
**Platform**: Windows 11 AMD64 22H2

I'm trying to learn Q2/Q3 style movement and I already know how to bhop so I decided to try binding the mousewheel to jump similar to Q1:

```
\bind mwheeldown +moveup
\bind mwheelup +moveup
```

And it does not register, except *very rarely*. I'm not sure what causes almost all of my input to get ignored.

Interestingly, this behavior also exists in classic Quake2 3.20 and another sourceport, [Q2Pro](https://skuller.net/q2pro/) BUT not the commercial Nightdive remaster (where `+moveup` can be spammed no-problem). Is this actually an intended feature? Is it a classic bhop safeguard of sorts? I don't know the history so excuse my ignorance.

EDIT: added yquake version (but is probably universal?)
EDIT: added platform information as well
EDIT: also test with remaster

**Comment by apartfromtime** [comment] 2024-05-12 02:22
Type this into the console or append it to your configuration file.

`\alias bhop "+moveup;wait;-moveup"`
`\bind mwheeldown bhop`
`\bind mwheelup bhop`

**Comment by Yamagi** [comment] 2024-05-25 14:22
The root cause is the mouse wheel handling code: Q2 expects that every key down event (key is pressed) is followed by a key up event (key is unpressed) at a later time. The mousewheel however sends only one event, indicating that it was moved. We work around hat by splitting this one event into an artificial key down event and right after that a key up event. That works for actions which only require an indicator that a button was pressed. Like changing the weapon. It doesn't work however for everything which required a button to be pressed for at least one frame. Jumping as movement action falls into the later category. I don't think that this can be fixed without too much hassle and risk breaking the fragile input state machine one again in some corner cases.

**Closed by Yamagi** 2024-05-25 14:22 UTC
