### ISSUE TITLE
Broken AI on Parasite on Ground Zero expansion pack

### ISSUE THREAD

**Issue by DarkSwan86** [yquake2/yquake2#359] opened 2019-01-20 13:27 UTC
Hi! I'm trying to finish Quake 2 and both expansion pack with Yamagi Quake 2 on the highest difficulty (Nightmare or ingame Hard+). 

I've noticed that on the expansion pack Ground Zero the AI for the Parasite (the 4 leg dog enemy that leeches you) is broken: when the enemy spots the player it run toward him and then run in place, never attacking him. 

A nice map to test this behaviour is Waste Processing (RSEWER1). I haven't tested the other difficulty levels. Thanks!

**Comment by Yamagi** [comment] 2019-01-30 16:48
Okay, I can reproduce it. Looks like it's happening on all difficulties. I'll look into it.

**Comment by Yamagi** [comment] 2019-01-30 17:35
That was easier then I thought. I just pushed a fix. We'll do a round of addon releases together with version 7.40 and this will be part of it. Thank you!

**Closed by Yamagi** 2019-01-30 17:35 UTC
