### ISSUE TITLE
software renderer stretches image ignoring aspect ratio  in vid_fullscreen 1

### ISSUE THREAD

**Issue by j4reporting** [yquake2/yquake2#661] opened 2021-01-31 13:14 UTC
with vid_fullscreen 1  the sw renderer stretches the selected game resolution to full desktop resolution. This is great, but it is ignoring the aspect ratio.

e.g.  desktop  is 2560x1440 
game resolution is 1600x1200

**Comment by Yamagi** [comment] 2021-01-31 15:28
I can reproduce that. @0lvin, can you have a look?

**Comment by 0lvin** [comment] 2021-01-31 22:04
By first look, if selected resolution has different aspect ratio, final image is stretched to full screen. That looks correct because `1` is render without change resolution.

I think we can ignore selected resolution and scale resolution to nearest resolution with same aspect ratio as the real screen resolution.

**Comment by Yamagi** [comment] 2021-02-11 16:30
I've merged the pull request. I think this is fixed. If not feel free to reopen the issue.

**Closed by Yamagi** 2021-02-11 16:30 UTC
