### ISSUE TITLE
cbe501a – Bug – Audio: SFX sound either reversed, out-of-sync, or play for the wrong entity – or completely missing

### ISSUE THREAD

**Issue by RavenMacDaddy** [yquake2/yquake2#917] opened 2022-10-10 08:25 UTC
[Video](https://youtu.be/_Fe1zx_sqOk)

I suppose it's related to the shared model loading PR that's mentioned in #910?

**Comment by Yamagi** [comment] 2022-10-12 10:50
Are you under Windows? If you are the updated openal32.dll in the last three test build is the likely culprit. I'll look into it. :)

**Comment by RavenMacDaddy** [comment] 2022-10-12 11:01
Correct, I'm running the client on Windows 11.

**Comment by Yamagi** [comment] 2022-10-13 18:07
@DanielGibson and me looked at the video and we are unsure what exactly is wrong. However, it is hard to notice subtle problems without having the direct feedback of the game. I played through the first four units and I'm pretty sure that there is no problem under Linux. Can you test:

* https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-testbuild-20221010-cbe501a-openal.zip This is the last testbuild repacked with an older openal32.dll. If it solves the problem the OpenAL update is the culprit.
* The last Release https://deponie.yamagi.org/quake2/windows/quake2-8.10.zip If it helps the sound changes in #869 are the likely candidate.

**Comment by RavenMacDaddy** [comment] 2022-10-16 12:58
Older OpenAL release didn't help (first link), playing the stable release it sounds like normal again; second link and already installed in another location.

**Comment by Yamagi** [comment] 2022-10-16 16:56
> Probably placebo, but it all sounds a lot better with the newer OpenAL version.

Very likely placebo. The update was from openal-soft 1.22.0 to 1.22.2. There are some smaller changes, but nothing important: https://openal-soft.org/

Anyways. Let's try it the other way round. 1346142283442c7f63e76205ad2fd3c9242a199f is an evil hack which removes the occlusion and reverb stuff merged last weekend from the OpenAL code path. A Windows build with the hack is here: https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-issue917-1346142.zip

**Comment by RavenMacDaddy** [comment] 2022-10-16 17:49
Here are the results: [Video](https://www.youtube.com/watch?v=fmWis0B169c)

Some very weird audio-entity associations going on.

Made a completely clean install, just to be sure.

Obviously, they share the same config file from `Documents`, but since the results are different because of different builds, it doesn't seem likely to be a factor.

Also, the fact that the config file itself doesn't contain anything of note that would be related to the issue at hand.

**Comment by Yamagi** [comment] 2022-10-16 20:08
I have an idea. Need to check it: My playthrough started with a new savegame and all my testing with `map $mapname`. I have never used old savegames. What if @0lvin inadvertently broke savegame compatibility? The savegame version was bumped, preventing the use of new savegames with the game related changes for the footsteps with old clients. But what about the other way round? Maybe the changes to the entity states break old savegames on new clients, when they are loaded assets get wrongly assigned or something like that.

**Comment by Yamagi** [comment] 2022-10-17 06:01
I hate it be right. It is indeed caused by older savegames loaded into a newer client. The saved entities reference the wrong sounds. A reproducer is attached. @RavenMacDaddy: Thank you very much for your help! Now it's up to me to figure something out :)
[soundbug.zip](https://github.com/yquake2/yquake2/files/9797296/soundbug.zip)

**Comment by RavenMacDaddy** [comment] 2022-10-17 08:13
No worries - I was eager to try a new game when I eventually get home.

**Comment by Yamagi** [comment] 2022-10-17 15:51
I have send a pull request with a possible fix. A Windows build with the fix is here: https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-20221017-80bd398-fix_savegame_compat.zip

**Comment by Yamagi** [comment] 2022-10-17 17:51
The opaque water fix isn't included. I'm still not convinced, that it is a good idea to apply it unconditionally. And I might have found an area were the same problem occurs without water. Another case of "you don't notice as long as you don't know it is there".

> Never even thought about that capability being a thing in the game – do you know if that feature is enabled in the original code by default? (It sounds really cool, and obviously makes for spacial awareness.)

It was first implemented in a fork of Q2RTX about a year ago: https://github.com/SkacikPL/Q2RTX @0lvin ported it to YQ2. The idea is rather obvious. In Vanilla Quake II some monster had footstep, for example the Tank and the Mutant. SkacikPL added tehm for all other monster. He even build the sound samples.

**Comment by RavenMacDaddy** [comment] 2022-10-17 18:21
> SkacikPL added them for all other monster. He even build the sound samples.

Okay, that's really sick.

**Closed** 2022-10-18 05:40 UTC
Labels: bug
