### ISSUE TITLE
[Bug?] Inaccessible body armor in Drilling Area (mine3)

### ISSUE THREAD

**Issue by StroggVorbis** [yquake2/yquake2#447] opened 2019-09-08 12:14 UTC
Near the crushers is a silo which contains a body armor. However, it can seemingly only be opened in Deathmatch, where the body armor is instead replaced with a megahealth. Did I miss something or is that an oversight on id Software's half? Using listentities items reveals that both the body armor AND megahealth are present in singleplayer and occupy the same space, however teleporting or noclipping inside only gives you the armor.

**Comment by DanielGibson** [comment] 2019-09-08 14:41
Maybe they just "forgot" the item or something; unless it's reachable (in SP) with the original quake2.exe from id and not with YQ2 (=> we introduced that bug) we should just treat it as intended behavior, as it's the way id have playtested it back in the day.

**Comment by Yamagi** [comment] 2019-09-09 05:44
Yes, that's it. Some levels have unreachable areas and there may be items in it, there're at least two unreachable monsters in baseq2 and maybe some more problems. These are oversights by id Software and won't can't be fixed by us.

**Comment by BjossiAlfreds** [comment] 2019-09-10 21:55
Issues with entity locations or spawnflags "can" be fixed by providing fixed ent strings for levels, but I don't think this should be in YQ2's scope. Someone interested could definitely start a separate project for fixing the level ent strings, using YQ2 as the base requirement to play it.

**Comment by Yamagi** [comment] 2019-09-11 06:04
> EDIT: Though on the other hand, it may not be a bad idea to replace all the disgusting map hacks in game.dll with fixed entity string files. Then people can take that effort further in their own personal mods/projects if they want.

If someone would do the work and the testing... :) We haven't done that many map hacks. The biggest one is the coop spawnpoint fixup that ensures that all players spawn in the location if the game isn't started in base1. But that's a function that finds and connects nearby spawnpoints and not a map hack in the real sense. Beside that there were some elevators hurting the player, mostly in the addons. We fixed the monster count in city3 and one secret somewhere in the mines if I remember correctly. And there maybe one or two more that I've forgotten about.

**Closed** 2019-09-15 07:42 UTC
