### ISSUE TITLE
Vsync doesnt properly match refresh rate

### ISSUE THREAD

**Issue by Nanotransistor** [yquake2/yquake2#222] opened 2017-07-30 02:22 UTC
When enabling vsync the framerate will lock at 59 which will cause a visible judder in the screen. Altering the maxfps variables doesnt seem to have any effect.

**Comment by maraakate** [comment] 2017-07-30 02:23
Operating system?  x86 or x64?  Video Card?  OpenGL1 or OpenGL3?

**Comment by Nanotransistor** [comment] 2017-07-30 15:04
Win 10 x64, R7 360 and with both versions of opengl.

**Comment by Yamagi** [comment] 2017-07-31 18:43
cl_drawfps is very, very inaccurate. Only one frame off is better than I would expect. Maybe one day we'll implement a new framecounter... Until then, is your displays refresh rate really 60hz and is cl_async set to 1 or to 0?

**Comment by Nanotransistor** [comment] 2017-08-01 22:28
async is set to 1, have tried it with zero as well. Monitor is 60hz too.

**Comment by Yamagi** [comment] 2017-08-02 09:20
Hmm... I'm unable to reproduce that. If cl_async ist set to 1 (the default) and the vsync is enabled the client enforces gl_maxfps == display refresh rate and cl_maxfps <= gl_maxfps. If cl_async is set to 0 gl_maxfps is always ignored and cl_maxfps determines the global frame rate. So there's no way that cl_maxfps > gl_maxfps which would lead to subtile stuttering. Can you describe the stuttering?

**Comment by Nanotransistor** [comment] 2017-08-02 16:35
It's more like a microstuttering, seems a few frames are a bit later than the rest. Hard to see, but my monitor has like zero blur so i notice it.

**Comment by Yamagi** [comment] 2017-08-02 18:45
I'm afraid that this is somewhat expected. At least with some OpenGL driver <-> display combinations. In a perfect world each frame takes about the same time to render. But with vsync enabled frames need to wait until the display is ready to display them. For example frame 1 doesn't need to wait, it's displayed immediately. Frame 2 needs to wait for 45ms. Frame 3 for 20ms. And so on... Some people may perceive this as stuttering. Quake II tries to mitigate this somewhat by capping the renderer framerate at the display refreshrate if vsync is enabled, however the lower the display  refreshrate is the lesser is the effect. The only real solution is to render more frames which may lead to tearing. :/

**Comment by Nanotransistor** [comment] 2017-08-02 22:24
Yeah i thought it may be a driver monitor thing, specially since AMD has always performed poorly with Opengl. It struck me as odd since it doesnt happen in other source ports though.

**Comment by Yamagi** [comment] 2017-08-03 05:35
Maybe it's the way how SDL 2 implementes the vsync. YQ2 has next to nothing to do with it, we just tell SDL 2 at the user requested the vsync to be enabled.

**Comment by Keith94** [comment] 2017-08-06 05:18
I get the same issue: On my 120 Hz display, enabling vsync in fullscreen caps the frame rate at 111 FPS. I can workaround this by running the game in windowed mode which properly syncs to the refresh rate.

**Comment by Yamagi** [comment] 2017-09-02 07:33
In the last days I've implemented a new, much more accurate frame counter and fixed several timing bugs. I can't promise that it'll solve the microstuttering issue but at least bothe the framecounter and Quake IIs framerate should match the display framerate if vsync is enabled. Can you give it a try? New Windows binaries can be found here: https://deponie.yamagi.org/quake2/misc/quake2-003b9a5.zip

**Comment by Nanotransistor** [comment] 2017-09-02 22:57
I tried it and i dont see any more microstutter. Runs super smooth now. Great work.

**Comment by Keith94** [comment] 2017-09-03 02:11
>Quake IIs real framerate should match the display framerate if vsync is enabled.

Can confirm that. 👍 
However my frame rate is still frequently jumping between ~95 and 120 FPS. Should ideally be smoothed out if possible.

**Comment by Yamagi** [comment] 2017-09-03 10:38
Very good. The problem ist just that this fix introduces new subtile timing issues, especially if the vsync is disabled and gl_maxfps is set to high values. So it'll need another rework...

**Comment by Yamagi** [comment] 2017-09-06 17:41
The fix is now in master and will be part of the next release. :)

**Closed by Yamagi** 2017-09-06 17:41 UTC
