### ISSUE TITLE
Yquake2 will not grab the mouse on Xubuntu 20.04

### ISSUE THREAD

**Issue by v322v322** [yquake2/yquake2#586] opened 2020-08-07 23:07 UTC
When I try to play yquake2 version  7.42+ctf1.06~dfsg-1 on Xubuntu 20.04, moving the mouse far enough in any direction activates the "workspace flipping" behavior.  The game continues to run, and if I move my mouse back to the workspace  I started yquake2 on, I can get back into the game.  This happens both in fullscreen and windowed mode.

**Comment by Yamagi** [comment] 2020-08-09 14:27
What is the `in_grab` cvar set to?

**Comment by DarkSwan86** [comment] 2020-08-09 20:20
I have the same problem! Manjaro KDE, latest update. I think the problem lies within Wayland. Usually i'm using my desktop with the Wayland session of KDE. When i try to fire on Yamagi quake 2 (left click of my mouse), the games goes into background and show me my desktop. If i'm using the x.Org session of KDE the problem doesn't occour. 

@v322v322 are you also on Wayland?

**Comment by DanielGibson** [comment] 2020-08-09 20:39
I don't think XUbuntu uses wayland, as far as I know XFCE doesn't support it yet.

Assuming `in_grab` isn't set to `0`, this is either a bug in SDL2 (or maybe it's not compiled with all the needed dependencies and/or options), or in Wayland or X11 or something else SDL2 uses to talk to the mouse.

**Comment by v322v322** [comment] 2020-08-12 04:19
Wayland is not running:
`loginctl `
`SESSION  UID USER SEAT  TTY `
`      2 xxxx xxxx seat0 tty2`
`     c1  126 gdm  seat0 tty1`

`$ loginctl show-session 2 -p Type`
`Type=x11`


`in_grab` is set to `2`.

In order to play, I have to go into the XFCE Window Manager settings and uncheck the "Wrap workspaces when reaching screen edge -> with mouse pointer" checkbox.

If this is an SDL2 bug, then I'll file a bug report with Ubuntu.

**Comment by DarkSwan86** [comment] 2020-08-14 15:02
With more testing i suspect that could be a problem with SDL not working correctly with Wayland. I have the exact same problem with Quakespasm (Quake 1 engine port) and GZDoom (Doom engine port). @v322v322 have you seen something similar on Ubuntu bug tracker?

**Comment by DanielGibson** [comment] 2020-08-29 21:07
After thinking a bit more about this, I don't think this is just weird behavior in XFCE, I think it's a proper bug.
If a Window has grabbed the mouse cursor (with `XGrabPointer()` which is what SDL2's `SDL_SetWindowGrab()` uses under the hood), XFCE **really** shouldn't release the mouse and switch the workspace when reaching the (fullscreen) window edges.
(I *assume* XFCE is to blame, but maybe it's really an X11 bug or something, I don't know how XFCE implements this weird feature)

**Comment by Yamagi** [comment] 2020-09-03 16:18
I'm unable to reproduce this on an up to date Arch Linux with KDE 5.19.something. Neither with X11, nor with Wayland. I've tested both xwayland and native wayland output, with `vid_fullscreen` set to `1` and `2`.

**Comment by Yamagi** [comment] 2020-10-31 15:36
Since this isn't a bug in YQ2 and we can't do anything about it, I'm closing here. If a possible work around that we can implement show up, feel free to reopen the issue.

**Closed by Yamagi** 2020-10-31 15:36 UTC
