### ISSUE TITLE
VSync lock lower than monitor refresh rate

### ISSUE THREAD

**Issue by dezo2** [yquake2/yquake2#277] opened 2018-02-11 09:15 UTC
Hi,
thank you for your work on this port. I have however one problem with last few versions including 7.10. When VSync is active, the FPS counter show 58.82 instead of 60 on my monitor and there is visible frame drop (or hitch) every 1 second. This is when I enable VSync in game. Sadly it is doing the same thing, when I leave VSync in game disabled and force it in nVidia Control Panel (GTX 1080). So there is no way for me to achieve smooth VSync. This is literally the only game which behaves like that, even old glQuake doesn't do this. I don't have any external frame limiter active. Is there maybe a cvar to make it work normally - I mean like any other engine? I tried fiddling with cl_maxfps, gl_maxfpsm cl_async but to no avail. My monitor refresh rate is 59.952 Hz (not exactly 60), but that's normal and it doesn't mean it has to be locked to 58.82 or something. Especially when the in game VSync is actually disabled.

PS: Right now I am using some ancient version 6.00pre of your port, which lock to 60 FPS normally, but it contains some AI bugs.

**Comment by Yamagi** [comment] 2018-02-11 17:10
Mkay, that one again. Seems like we need to look into this. Some thoughts:

* The framecounter in all versions before 7.02 is very inaccurate. It's likely that it shows 60 fps but that the actual value is much lower. Probably somewhere around 55 fps. That was caused by wrong measurements, wrong calculations and a wrong scale.
* Quake II is able to hold the request framerate (the displays framerate if vsync is enabled) just fine. But in some cases, until now I thought that it only happens with Radeons on Windows, we're loosing about one frame per second in SDL_GL_SwapWindow(). The functions just doesn't return in time.
* The time loss in SDL_GL_SwapWindow() is much pronounced when running in windows mode.
* At least on my Radeon the time loss is mich higher when running with GL3 instead of GL1. With GL1 the game nearly capable of holding the displays framerate, with GL3 it's 1 or 2 frames off.

My guess is that we're seeing another issue somewhere in SDL or the GPU drivers. @DanielGibson, do have any idea?

**Comment by DanielGibson** [comment] 2018-02-11 18:06
Maybe the display compositor (I think it's called WDM on windows?) is the problem here?
What version of Windows do you use? I know that in Win7 it can be disabled (classic mode instead of aero mode) and that this improves the performance of games a lot (many modern games do this automatically).
You could also (if you're not in Win7 or in addition to classic mode) try to run the game in "real" fullscreen (`vid_fullscreen 2`), at your displays native resolution.

**Comment by ericwa** [comment] 2018-02-11 19:28
I'm curious about this - our vsync code in Quakespasm needs to be rewritten and I've been wondering how to fix it.

What I'm thinking is that the safest way to use vsync is always server/client/renderer frames as soon as `SDL_GL_SwapWindow` returns control to the game. If you wait further into the VSync interval you risk missing the swap time.

Is it possible the `renderdelta` clock in `Qcommon_Frame` is drifting relative to the VSync clock, so you go from rendering a frame at the beginning of the vsync interval (good), and then a few seconds later it's drifted so you're starting frame rendering at the end of the vsync interval (bad) and eventually miss it? Should be easy to check by logging the timestamp of when `SDL_GL_SwapWindow` returns as well as when the `CL_Frame` for rendering happens.

**Comment by dezo2** [comment] 2018-02-11 20:18
Sorry I forgot - using win 7 x64 here. For gaming Aero is disabled and all games are set to fullscreen. Anyway, I really don't think performance is a problem with this GPU. It basically sits in idle state while playing yq2 with VSync. Out of curiosity I forced max. power in NVCP for the game, but it's the same. Also tried that mentioned cvar vid_fullscreen=2, but no cigar - it still sits at 59 FPS no matter what. Last thing I can do is disable VSync and use RTSS (from MSI Afterburner package) to limit FPS exactly to refresh rate, but without VSync, tearing is inevitable.

My knowledge is very limited on this, but maybe there is some problem with internal timer precision when preparing frames for presentation in VSync event. It is even necessary to limit frames when using VSync? I thought its all about preparing one/two frames for presentation (to minimize input lag) and then wait for VBlank event itself (doing something else like physics / ai / input scan), before preparing another frames - so no timer/limiter involved. But I can be totally wrong... :-)

**Comment by DanielGibson** [comment] 2018-02-11 20:22
It's not just pure performance (from an "compositors add x% overhead" point of view), compositors add an additional level of buffering and that at least delays frames, and can possibly have its own timing problems that *may* cause occasionally lost frames (or vsync taking too long).

But if you're using Win7 with Aero disabled this shouldn't be the problem - unfortunately, I have no idea what else could cause this.

**Comment by Yamagi** [comment] 2018-02-11 21:01
@ericwa: At least in Quake II the whole internal timing was utterly broken from the beginning. It has a lot of bugs and design problems, apparently it was hacked together in a kind of trial and error process until it worked. The problem is that the whole game physics and mechanics, movement predicitons and even the network protocol depend on this broken crap... It took me endless hours until I got the async client and vsync working.

> Is it possible the renderdelta clock in Qcommon_Frame is drifting relative to the VSync clock, so you go from rendering a frame at the beginning of the vsync interval (good), and then a few seconds later it's drifted so you're starting frame rendering at the end of the vsync interval (bad) and eventually miss it? 

This might be indeed a problem. I'll need to take a deeper look in the next few to days to see if it's really the case.

**Comment by DanielGibson** [comment] 2018-02-11 21:45
if you set `cl_drawfps 3`, what kind of values do you get for "max" (in "ms")? Just play for a minute or so and look at the numbers, they'll probably vary slightly, but not much (ignore the first few seconds after starting the game).
I usually get something like "max 17.45ms, Min: 15.58ms, Avg: 16.98ms", and like you I also get around 58.9fps, instead of 59.95 or 60.
(This is on Linux, nvidia, XFCE, no compositor; if I use the compton compositor max often is > 32ms, which means that frames definitely were missed)

Oh, and another thing: Do you have more than one display? Could be that the driver does weird things when more than one display is connected (and the displays maybe have slightly different timings)? Just guessing here (I have two different displays).

**Comment by dezo2** [comment] 2018-02-11 22:05
@DanielGibson: Most of the time I am seeing [max: 18.00, min: 16.00, avg: 17.00] ms. Pretty much consistently in this range. Tried also with Aero and max went over 30 ms then.

As for my monitor, i have only one. Nothing fancy, 2560x1440 @60Hz native, connected via DVI.

**Comment by Yamagi** [comment] 2018-02-12 17:21
Mkay, I've found two problems. SDL may return the wrong display refresh rate, resulting in Quake II rendering too few frames. And the Windows power management may interfere with the delay in Quake IIs mainloop. Here's a set of new binaries: https://deponie.yamagi.org/quake2/misc/quake2-68e147d.zip

There're 2 new cvars:

* `vid_displayrefresh` let the user override the detected refresh rate. Can you test with this one set to 60?
* If that doesn't help please set `cl_busywait` to 1. With that set Quake II will consume a whole CPU core but the power management won't interfere. This may push laptops into throtteling.

**Comment by dezo2** [comment] 2018-02-12 18:24
Hi,
thanks for the new binaries. Started the port, loaded a saved game ->FPS 58.82. Then I have set:
vid_displayrefresh 60, vid_restart -> 58.82
cl_busywait 1, vid_restart -> 58.82
Restarted whole game, checked if both cvars are set, still 58.82. During loading in the console, after the vid_restart command, FPS counter clearly shows 59.95. But as soon as the level is loaded, it goes straight back to 58.82. In the FPS counter info, min FPS varies in range 55.56 - 58.82, max FPS in range 58.82 - 62.5, if that helps with anything. Renderer is OpenGL 1.4.

PS: Is there a difference between quake2.exe and yquake2.exe? They behave the same.

**Comment by DanielGibson** [comment] 2018-02-12 18:26
yquake2.exe is the real thing, quake2.exe is just a simple wrapper that starts it (for backwards compat reasons, if people have shortcuts to quake2.exe etc)

**Comment by Yamagi** [comment] 2018-02-13 08:11
Hi,
another try, please: https://deponie.yamagi.org/quake2/misc/quake2-54f3b1b.zip There's no need to set any cvars, everything should work out of the box. There're 3 changes in this build:

* Add a hack to work around wrongly reported display refresh rates and some small inaccuracies in Quake IIs internal timing.
* When calculating the internal timings take the time spend to process and render the frame into account. Without this the game is running a little bit too slow.
* Refine the delay between two frames from a sleep to a spinlock. This will consume somewhat more CPU power but is (at least on Windows) much more accurate.

Let's hope that this works. I don't see any more ways to fix this on Quake IIs side. :/

**Comment by dezo2** [comment] 2018-02-13 09:09
YES! Seems to be fixes now, thank you very much :-)
FPS counter shows 59.95 all the time and hiccups are gone.

**Comment by Yamagi** [comment] 2018-02-13 09:20
Very good. Thank you for testing and reporting this! The changes will be part of version 7.20, to be released in early march.

**Closed by Yamagi** 2018-02-13 09:20 UTC
