### ISSUE TITLE
Potential MP prediction errors due to floating point stuff

### ISSUE THREAD

**Issue by DanielGibson** [yquake2/yquake2#237] opened 2017-09-17 00:22 UTC
Mara pointed the following potential issue out that at least affected q2 ports in the past:
We should check if we get many/large prediction errors (`cl_showmiss 1`) in multiplayer, and if it goes away when building with `-float-store` or `-ffast-math -fsingle-precision-constant`.
I think this especially can happen when using the original Q2 windows client (or any built with MSVC?) on a Linux dedicated server.

> <[HCI]Mara> i also found out that the linux builds must be rounding the floating point incorrectly compared to windows
> <[HCI]Mara> you can connect to a linux ded server and hug walls and get "stuck" into them with prediction errors
> <[HCI]Mara> and its always been this way
> <[HCI]Mara> now if you use a linux client and connect to a linux server its fine though
> <[HCI]Mara> i see dk 1.3 for pandora does -ffast-math -fsingle-precision-constant
> <[HCI]Mara> so maybe whoever did that PANDORA build ran into the same issue and forgot to tell us
> <[HCI]Mara> b5930:
> <[HCI]Mara>   * Fixed precision differences on Linux binaries causing prediction errors for the majority of clients. An example of this is in The Edge (q2dm1) when going from the SSG to the MH room and hugging the wall - near the top of the steps, you will experience large prediction errors. Note, if building your own Q2 client for Linux, be sure to specify -ffloat-store in the gcc command line or your client will mispredict.

(that is from the r1q2 changelog: https://pastebin.com/v8eb3uVw)

> <[HCI]Mara> that fixed it
> <[HCI]Mara> bah
> \<caedes> wtf
> <[HCI]Mara> you may want this in yq2 btw
> <[HCI]Mara> you may want to verify the behaviour in yq2 in DM if you can
> <[HCI]Mara> turn on cl_showmiss 1
> <[HCI]Mara> and huge the walls in those areas and it will probablyh ave a hissy fit
> <[HCI]Mara> if youre compiling with mingw as well it will be the same issue
> <[HCI]Mara> i have to test q2dos but it probably needs it too
> <[HCI]Mara> i saw that linux also a comparable controlfp function to force the 24-bit floating point per tick in the main loop
> <[HCI]Mara> since windows does that
> <[HCI]Mara> idk if it matters, but i havent seen any prediction errors since applying -ffloat-store to DK 1.3 we just tested it for an hour

**Comment by Pickle** [comment] 2017-09-17 12:26
Daniel,

Its likely I did the pandora build mentioned and theres a good chance I
used -fsingle-precision-constant.
But Ive never tried MP with a pandora build.

Scott

**Comment by maraakate** [comment] 2017-09-17 16:49
Hi Scott, for the record i had to use -ffloat-store to fix the prediction misses.  Setting -fsingle-precision-constant and -ffast-math did nothing to change it.  DarkPlaces goes out of it's way to mention that you DO NOT use -ffast-math for Quake engine ports.  Might be worth talking to LadyHavoc on this issue as well.

**Comment by maraakate** [comment] 2017-09-17 16:50
> 9:54:15 PM) ladyhavoc: I think using --msse2 may work too
(9:55:03 PM) ladyhavoc: truncating the floats between operations is something that x87 fpu is not good at, and -ffloat-store makes it slower but brings consistency
(9:55:16 PM) ladyhavoc: whereas using SSE/SSE2 instructions is always truncated correctly
(9:55:27 PM) ladyhavoc has left the conversation
(10:06:29 PM) ladyhavoc has gone away.
(10:10:40 PM) maraakate: yes well when i did testing with q2dos years ago i noticed ffloat-store did slow it down a litle in timedemos
(10:10:43 PM) maraakate: like 3-4 fps on average
(10:10:56 PM) maraakate: so sse2 targeting isnt an option for DOS 
(10:10:57 PM) maraakate: but yeah
(10:11:05 PM) maraakate: are you targetting sse2 or using ffloat-store?
(10:11:15 PM) maraakate: or is it even a problem with darkplaces since i know its a different type of protocol
(10:15:51 PM) ladyhavoc is no longer away.
(10:16:52 PM) ladyhavoc: darkplaces 32bit builds use x87 fpu, except for some specific routines that are SSE2 (especially the software rasterizer)

**Comment by maraakate** [comment] 2017-09-17 16:52
From darkplaces makefile.inc

> # Normal
CPUOPTIMIZATIONS?=-fno-math-errno -ffinite-math-only -fno-rounding-math -fno-signaling-nans -fno-trapping-math
# NOTE: *never* *ever* use the -ffast-math or -funsafe-math-optimizations flag

**Comment by Yamagi** [comment] 2017-09-19 08:22
I did some code digging and background reading. A good article about floating point problems is: https://arxiv.org/pdf/cs/0701192.pdf

The root cause of these problems is that the movement, the physics calculations (in server / game) and the movement prediction (in client) are implemented in floating point arithmetic and not in integer arithmetic. Floating point arithmetic is imprecise by design. Additionally there are several implicit casts from float to integer, each one of these leads to a loss in precision. For example 42.23 becomes just 42. That's at least part of the "zero has gravity" bug. And last but not least the network protocol works with shorts. To mitigate the precision loss when converting float -> short -> float the code uses the old and dirty "multiply by 8" trick. float * 8 -> short -> float * 0.125, for example 42.23 * 8 = 337.84 -> 337 -> 337 * 0.125 = 42.125.

The specific problem (misspredictions between platforms) is caused by different floating point implementations and modes. id Softwares original client set the x87 control word to single precision: https://github.com/id-Software/Quake-2/blob/master/win32/sys_win.c#L655 But it only did that on Win32. So there are 3 cases:

* Original client (build with MSVC) on Windows: Single Precision
* Original client and most / all source ports on Linux / Unix / Mac i386: Extended Double Precision
* Original client on everything that's not i386: Double Precision

Compiling on Linux / Unix / Mac i386 `-ffloat-store` somewhat lessens the problem. It forces a register flush after each floating point instruction, more or less rounding down from extended double precision to double precision. But it's not really correct since it effectively introduces a fourth case. And the option is only implemented by GCC, not by Clang nor any other compiler.

I see two options:

* Don't fix it. It has been broken since ever and so far no one complained. Especially the common case YQ2 32 bit binary on Windows (we've removed setting the x87 control word long ago) against YQ2 64 bit binary on Linux (Linux/i386 is in a state of apparent death for server and desktop use) hasn't got the problem.
* Build YQ2 on i386 with `-msse2 -mfpmath=sse` to force double precision. This should be okay since the 64 bit Linux binaries used douple precision since ever. It would solve the YQ2 32 bit binary on Windows against YQ2 32 bit binary on Linux case and help the original client and other source ports against YQ2 32 bit on Linux. But it we would lose support for CPUs without SSE2, everything up to Pentium III and Athlon XP.

**Comment by maraakate** [comment] 2017-09-19 11:46
Another option is that linux itself has a controlfp-like function.  DJGPP has it, we use it on q2dos and we don't use ffloat-store and I verified yesterday that movement is correct.

* http://www.delorie.com/djgpp//doc/libc-2.02/libc_101.html
* http://man7.org/linux/man-pages/man3/fenv.3.html

If you did it for x86 this would allow you to continue supporting P3 and AXP and allow x64 to take care of the rest.

**Comment by maraakate** [comment] 2017-09-20 00:07
See also: http://man7.org/linux/man-pages/man3/__setfpucw.3.html

**Comment by Yamagi** [comment] 2017-09-21 16:41
I've just pushed a fix master. It forces the x87 FPU to work in double precision (64 bit) mode. Additionally -ffloat-store is set when building with gcc for i386. Out of paranoia I've forced x86_64 to use SSE math. That should be a no-op, since every sane compiler should do that anyways.

Thank you all for your help :)

**Closed by Yamagi** 2017-09-21 16:41 UTC
