### ISSUE TITLE
Windowed mode

### ISSUE THREAD

**Issue by Zbiten** [yquake2/yquake2#929] opened 2022-10-24 19:05 UTC
Hello.
Cant switch to windowed mode. It doesnt work. Choose, Apply and nothing happened, still fullscreen.

**Comment by protocultor** [comment] 2022-10-24 19:29
Which operating system? And renderer (OGL 3.2 or 1.4)?
Which are the contents of your qconsole.log? (messages on your console)

**Comment by Zbiten** [comment] 2022-10-24 23:25
Win10 x64. I tried with OGL 3.2 and Vulcan. Stable version of yquake2 and october betas.
[qconsole.log](https://github.com/yquake2/yquake2/files/9855966/qconsole.log)
Vulcan render like me better, more colorful and juicy.

**Comment by protocultor** [comment] 2022-10-25 00:26
Can't see anything wrong with the log either. Have you tried running with the following parameters:
"+set vid_fullscreen 0"

**Comment by Zbiten** [comment] 2022-10-25 01:21
> +set vid_fullscreen 0

No, but i tried to create autoexec.cfg in xatrix folder, add "set vid_fullscreen 0" and launch with this.

**Comment by protocultor** [comment] 2022-10-25 15:18
**Don't** use a propietary launcher like Steam when trying to test for a possible bug.

Execute "quake2.exe" directly without passing through Steam, and try to go windowed.
If you can, then Steam Overlay is the culprit of all of this.
If it complaints you aren't running Steam instead, you didn't do a proper installation of YQ2, because that's the Steam executable.

Unrelated to all of this, unless you have a specific problem with The Reckoning, `xatrix` is the wrong folder to put your autoexec.cfg; you were looking for `baseq2`.

I believe it's time to close this.

**Comment by maraakate** [comment] 2022-10-25 15:21
I will say, from personal experience, I have had bug reports on DK 1.3 causing funny things and the root cause ended up being the steam overlay.

**Comment by Zbiten** [comment] 2022-10-25 15:57
> Execute "quake2.exe" directly without passing through Steam, and try to go windowed.
The same. Only when launch via yquake2.exe windowed mode works.
2) Autoexec.cfg in base2 folder too.
3) Always disable Steam Overlay when install old games.
Okay, you can close this topic, but the issue still remains.

**Closed** 2022-10-26 19:47 UTC

**Comment by protocultor** [comment] 2022-10-26 21:15
I know this is over, but here: https://www.reddit.com/r/quake/comments/vtr4ef/comment/if9e2u2/?context=3
...found a decent idea: swap names between yquake2.exe and quake2.exe files. It should even work with Steam.

**Comment by Zbiten** [comment] 2022-10-26 21:27
> ...found a decent idea: swap names between yquake2.exe and quake2.exe files. It should even work with Steam.

Already tried, 2d ago, and it`s strange but doesnt working. The Reckoning completed 1d ago, GZ - half of missions. I think i can complete with this problem. It`s not critical, but sometimes i need to alt+tab and this isnt working in fullscreen mode. That`s why i open issue here.
