### ISSUE TITLE
Bug – Water: GFX (particles) don't render as long as the player is at least partially underwater 

### ISSUE THREAD

**Issue by RavenMacDaddy** [yquake2/yquake2#910] opened 2022-10-02 20:43 UTC
Examples:

* Particle effects; blood and from gun shots
* Explosions, e.g., when killing a Flyer

Tested with both OpenGL 3.2 and Vulkan, so it's seemingly not isolated to a particular API.

Specs:

OS: Windows 11 – 22621.608
GPU: GeForce GTX 1080 (driver v512.95)

Don't recall at the moment if this affects SFX as well, though I've a vague memory that it does – possibly correlating with the GFX that doesn't render.

**Comment by Yamagi** [comment] 2022-10-08 14:32
@DanielGibson and me gave it a try and we are so far unable to reproduce it. Can you tell us a location where we can reproduce it? The map and coordinates to teleport to (output of the `viewpos`) command would be nice.

**Comment by RavenMacDaddy** [comment] 2022-10-08 15:46
Unit 3: Level 1: Main Gate – right after the first door down in the water

https://www.veed.io/view/00fe84d7-d2d4-4f2a-a702-b2ea125421ae/showcase?sharingWidget=true

Seems like if I'm at the top of the surface it's rendering as expected, while if I'm submerged in water it's only expecting the effects to rendered below the water, nothing above.

**Comment by Yamagi** [comment] 2022-10-08 17:41
Thank you, the video helped a lot. This is caused by the server filtering out the explosion entity before sending it to the server. This is caused somehow(tm) by the server thinking that the player and the explosion aren't both in the 'player hearing set' or 'player viewing set': https://github.com/yquake2/yquake2/blob/master/src/server/sv_send.c#L232

We'll have a deeper look, **but** this is really deep in this "what can been seen and heard" magic and is likely unfixable. Something like the map compiler took the water surface (the surface in the video is not transparent) as an implicit area portal and cutting of the connection to the area above the water.

**Comment by RavenMacDaddy** [comment] 2022-10-08 18:18
That last sentence and analogy made a lot of sense and created clarity of the situation; the game is handling (interpreting) the environment like there are two completely different areas that the player is passing through (like a portal, as you worded it), and therefore the other is essentially discarded.

**Comment by DanielGibson** [comment] 2022-10-08 18:57
The weird thing is that this only happens at some places.
Near the place of your video there's a pipe that you can swim through to get to another similar area (on the other side of the building), and in the pipe and on the other side this issue does not happen.
It didn't happen in other places with opaque water that we tested either, for example in that bonus map with the train (train.bsp aka Lost Station).

So I think this was probably bug in the map compiler?

**Comment by RavenMacDaddy** [comment] 2022-10-08 19:20
Now that you mention it, I completely forgot about that; I was trying to reproduce this issue in another map I was playing, later in the game, and I was unable to, so I speedran the game to a point where I knew I saw it happening.

There might be other maps or spots where it's occurring, but that example will have to do for now for me personally.

**Comment by DanielGibson** [comment] 2022-10-09 16:32
Maybe I found a workaround after all, but it's a bit ugly and I'm not sure at all if it doesn't break other things, will require extensive testing (I guess Yamagi will provide updated Windows binaries soonish?)

**Comment by RavenMacDaddy** [comment] 2022-10-09 16:51
I don't doubt I'd be up for testing a pre-release build just playing the game like normal (or specific scenarios if needed of course).

Sure, Quake 2 is not as tight gunplay as the first - however it's so easy to play and enjoy while doing so.

**Comment by Yamagi** [comment] 2022-10-10 06:17
A Windows build with this fix and the shared model loading PR is here: https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-testbuild-20221010-cbe501a.zip

The code can be found in this branch: https://github.com/yquake2/yquake2/tree/testbuild-20221010

**Comment by RavenMacDaddy** [comment] 2022-10-10 08:42
At least for the same spot as referenced here from the Main Gate map, it's working just perfectly.

[Video](https://youtu.be/pN_1PK2uqB4)

**Comment by Yamagi** [comment] 2022-10-12 10:48
I've played through the first 4 units with the patch applied and encountered no problem so far.

**Comment by Yamagi** [comment] 2022-11-06 17:15
I've merged the work around into master.

**Closed by Yamagi** 2022-11-06 17:15 UTC
Labels: bug
