### ISSUE TITLE
Linux v5.3.1 : Ogg playback interrupted by other sounds

### ISSUE THREAD

**Issue by ewe2** [yquake2/yquake2#92] opened 2015-10-11 13:17 UTC
This is an odd one: the "computer update" sound interrupts ogg playback within levels but not at the beginning of levels (or subsections). I've noticed door/lift noises also interrupt playback. This seems to affect the loop of the soundtrack, and it only resets when starting/restarting a level/subsection.

**Comment by DanielGibson** [comment] 2015-10-11 13:24
OpenAL or SDL sound?

**Comment by ewe2** [comment] 2015-10-11 13:38
I didn't mess with the makefile so its most likely OpenAL sound because I'm using SDL2.0.

**Comment by DanielGibson** [comment] 2015-10-11 14:34
SDL2 also supports sound, so whether you're using SDL1 or SDL2 doesn't make a difference in that regard.

When you start the game, in the console there should be the following lines (amongst others):
```
Client build options:
 + SDL2
 - CD audio
 + OGG/Vorbis
 + OpenAL audio
 + Zip file support
```
does it say "OpenAL audio" there?

A bit further down there should be something like
```
------- sound initialization -------
LoadLibrary(libopenal.so.1)
...opening OpenAL device:ok
...creating OpenAL context: ok
...making context current: ok
```

does it look the same for you, or is there something about SDL after `------- sound initialization -------`?

**Comment by ewe2** [comment] 2015-10-11 20:30
------- sound initialization -------
LoadLibrary(libopenal.so.1)
...opening OpenAL device:ok
...creating OpenAL context: ok
...making context current: ok

OpenAL settings:
AL_VENDOR: OpenAL Community
AL_RENDERER: OpenAL Soft
AL_VERSION: 1.1 ALSOFT 1.16.0
AL_EXTENSIONS: AL_EXT_ALAW AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_IMA4 AL_EXT_LINEAR_DISTANCE AL_EXT_MCFORMATS AL_EXT_MULAW AL_EXT_MULAW_MCFORMATS AL_EXT_OFFSET AL_EXT_source_distance_model AL_LOKI_quadriphonic AL_SOFT_block_alignment AL_SOFT_buffer_samples AL_SOFT_buffer_sub_data AL_SOFT_deferred_updates AL_SOFT_direct_channels AL_SOFT_loop_points AL_SOFT_MSADPCM AL_SOFT_source_latency AL_SOFT_source_length

Available OpenAL devices:
- Simultaneous output to Built-in Audio Analog Stereo
- Built-in Audio Analog Stereo

Current OpenAL device:
- OpenAL Soft

Number of OpenAL sources: 31

**Comment by ewe2** [comment] 2015-10-11 20:30
Using pulseaudio as well if that helps.

**Comment by ewe2** [comment] 2015-10-12 07:39
I'm wondering if it isn't some kind of phase cancellation issue, I'm hearing attack sounds on my extreme left of stereo field in headphones which are obliterated by the ogg playback when they're right in front of me (eg the monsters in the Guard House section), and a couple of times the F1 computer update definitely stops the music dead (but perhaps cancels it out so its actually still playing).

**Comment by deuxsonic** [comment] 2015-10-12 10:29
I actually stopped using OpenAL in it because of anomalies like sounds playing to just left channel or just right channel and sounds sounding like they're distorted/underwater.

**Comment by DanielGibson** [comment] 2015-10-12 18:00
Can you try using the latest code from Git?

**Comment by ewe2** [comment] 2015-10-12 20:45
I've been using the git code from the start. I'm using OpenAL-soft 1.16, made sure I have a clean .alsoftrc, and I noticed too that ogg_autoplay was set to "?" so set it to "1". None of this has made any difference. I notice that if i set ogg_play specifcally, the events that stop playback (like the laser drills in the mines) result in an ogg_pause status.

**Comment by DanielGibson** [comment] 2015-10-12 21:20
you wrote "Linux  v5.3.1" so I was assuming you're using the 5.31 release code, not latest git.

anyway, can you give us an easy description to reproduce the problem, like a level (ideally the mapname for `/map bla` in the console) it happens in and where, maybe a screenshot of the place it happens at?

@deuxsonic at least the "just left channel or just right channel" (especially when using headphones or even HRTF?) shoud be fixed with a recent commit, you may wanna try  with latest code again :-)
Sounds sounding distorted/underwater should only happen underwater, if it happens somewhere else we'd be glad about more information on how to reproduce that problem.

**Comment by deuxsonic** [comment] 2015-10-12 22:35
It's not really an underwater effect, that's what it reminds me of though because the volume kind of jumps all over during playback of a sound.

**Comment by DanielGibson** [comment] 2015-10-12 22:38
ok.. well, try latest git, it *kind of* sounds like the bug https://github.com/yquake2/yquake2/commit/432fdc271b41551ea60c957aab67da3f4afd019b was supposed to fix.

**Comment by ewe2** [comment] 2015-10-13 09:23
I'll get something for you tonight Daniel.

**Comment by ewe2** [comment] 2015-10-13 10:42
Here is a quick qconsole.log using /map mine4 in godmode and quickly getting down to the laser and pressing the button at which point ogg playback pauses and has to be manually restarted.

Console initialized.

------- sound initialization -------
LoadLibrary(libopenal.so.1)
...opening OpenAL device:ok
...creating OpenAL context: ok
...making context current: ok

OpenAL settings:
AL_VENDOR: OpenAL Community
AL_RENDERER: OpenAL Soft
AL_VERSION: 1.1 ALSOFT 1.16.0
AL_EXTENSIONS: AL_EXT_ALAW AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_IMA4 AL_EXT_LINEAR_DISTANCE AL_EXT_MCFORMATS AL_EXT_MULAW AL_EXT_MULAW_MCFORMATS AL_EXT_OFFSET AL_EXT_source_distance_model AL_LOKI_quadriphonic AL_SOFT_block_alignment AL_SOFT_buffer_samples AL_SOFT_buffer_sub_data AL_SOFT_deferred_updates AL_SOFT_direct_channels AL_SOFT_loop_points AL_SOFT_MSADPCM AL_SOFT_source_latency AL_SOFT_source_length

Available OpenAL devices:
- ALSA Default
- HDA Intel PCH, ALC887-VD Analog (CARD=PCH,DEV=0)
- HDA Intel PCH, ALC887-VD Digital (CARD=PCH,DEV=3)
- HDA NVidia, HDMI 0 (CARD=NVidia,DEV=3)
- HDA NVidia, HDMI 1 (CARD=NVidia,DEV=7)

Current OpenAL device:
- OpenAL Soft

Number of OpenAL sources: 31

Starting Ogg Vorbis.
OGG_LoadPlaylist: could not open playlist: No such file or directory.
10 Ogg Vorbis files found.
OGG_OpenName: '1' not in the list.
Sound sampling rate: 0
------------------------------------

----- refresher initialization -----
Byte ordering: little endian

Refresher build options:
 + Retexturing support
 - Gamma via X11
Refresh: Yamagi Quake II OpenGL Refresher
SDL video driver is "x11".
setting mode 16: 1280 1024
Got 8 bits of stencil.
Using hardware gamma via SDL.

OpenGL setting: GL_VENDOR: NVIDIA Corporation GL_RENDERER: GeForce GT
730/PCIe/SSE2 GL_VERSION: 4.4.0 NVIDIA 340.76 GL_EXTENSIONS:
GL_AMD_multi_draw_indirect GL_AMD_seamless_cubemap_per_texture
GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_bindless_texture
GL_ARB_blend_func_extended GL_ARB_buffer_storage GL_ARB_clear_buffer_object
GL_ARB_clear_texture GL_ARB_color_buffer_float GL_ARB_compatibility
GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth
GL_ARB_compute_shader GL_ARB_compute_variable_group_size GL_ARB_copy_buffer
GL_ARB_copy_image GL_ARB_debug_output GL_ARB_depth_buffer_float
GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_draw_buffers
GL_ARB_draw_buffers_blend GL_ARB_draw_indirect
GL_ARB_draw_elements_base_vertex GL_ARB_draw_instanced GL_ARB_enhanced_layouts
GL_ARB_ES2_compatibility GL_ARB_ES3_compatibility
GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location
GL_ARB_fragment_coord_conventions GL_ARB_fragment_layer_viewport
GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader
GL_ARB_framebuffer_no_attachments GL_ARB_framebuffer_object
GL_ARB_framebuffer_sRGB GL_ARB_geometry_shader4 GL_ARB_get_program_binary
GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_half_float_pixel
GL_ARB_half_float_vertex GL_ARB_imaging GL_ARB_indirect_parameters
GL_ARB_instanced_arrays GL_ARB_internalformat_query
GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata
GL_ARB_map_buffer_alignment GL_ARB_map_buffer_range GL_ARB_multi_bind
GL_ARB_multi_draw_indirect GL_ARB_multisample GL_ARB_multitexture
GL_ARB_occlusion_query GL_ARB_occlusion_query2 GL_ARB_pixel_buffer_object
GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_program_interface_query
GL_ARB_provoking_vertex GL_ARB_robust_buffer_access_behavior GL_ARB_robustness
GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map
GL_ARB_seamless_cubemap_per_texture GL_ARB_separate_shader_objects
GL_ARB_shader_atomic_counters GL_ARB_shader_bit_encoding
GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote
GL_ARB_shader_image_load_store GL_ARB_shader_image_size GL_ARB_shader_objects
GL_ARB_shader_precision GL_ARB_query_buffer_object
GL_ARB_shader_storage_buffer_object GL_ARB_shader_subroutine
GL_ARB_shader_texture_lod GL_ARB_shading_language_100
GL_ARB_shading_language_420pack GL_ARB_shading_language_include
GL_ARB_shading_language_packing GL_ARB_shadow GL_ARB_sparse_texture
GL_ARB_stencil_texturing GL_ARB_sync GL_ARB_tessellation_shader
GL_ARB_texture_border_clamp GL_ARB_texture_buffer_object
GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_buffer_range
GL_ARB_texture_compression GL_ARB_texture_compression_bptc
GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map
GL_ARB_texture_cube_map_array GL_ARB_texture_env_add
GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3
GL_ARB_texture_float GL_ARB_texture_gather GL_ARB_texture_mirror_clamp_to_edge
GL_ARB_texture_mirrored_repeat GL_ARB_texture_multisample
GL_ARB_texture_non_power_of_two GL_ARB_texture_query_levels
GL_ARB_texture_query_lod GL_ARB_texture_rectangle GL_ARB_texture_rg
GL_ARB_texture_rgb10_a2ui GL_ARB_texture_stencil8 GL_ARB_texture_storage
GL_ARB_texture_storage_multisample GL_ARB_texture_swizzle GL_ARB_texture_view
GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3
GL_ARB_transform_feedback_instanced GL_ARB_transpose_matrix
GL_ARB_uniform_buffer_object GL_ARB_vertex_array_bgra
GL_ARB_vertex_array_object GL_ARB_vertex_attrib_64bit
GL_ARB_vertex_attrib_binding GL_ARB_vertex_buffer_object GL_ARB_vertex_program
GL_ARB_vertex_shader GL_ARB_vertex_type_10f_11f_11f_rev
GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_ARB_window_pos
GL_ATI_draw_buffers GL_ATI_texture_float GL_ATI_texture_mirror_once GL_S3_s3tc
GL_EXT_texture_env_add GL_EXT_abgr GL_EXT_bgra GL_EXT_bindable_uniform
GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate
GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_compiled_vertex_array
GL_EXT_Cg_shader GL_EXT_depth_bounds_test GL_EXT_direct_state_access
GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_draw_range_elements
GL_EXT_fog_coord GL_EXT_framebuffer_blit GL_EXT_framebuff

Probing for OpenGL extensions:
...using GL_EXT_compiled_vertex_array
...using GL_EXT_point_parameters
...GL_EXT_shared_texture_palette not found
...ignoring GL_ARB_multitexture
...using GL_EXT_texture_filter_anisotropic
...using GL_ARB_texture_non_power_of_two
...using GL_ARB_texture_env_combine
------------------------------------

------- input initialization -------
------------------------------------

-------- game initialization -------
LoadLibrary("game.so")
Game is starting up.
Game is baseq2 built on Oct 12 2015.
------------------------------------

------- server initialization ------
0 entities inhibited.
0 teams with 0 entities.
------------------------------------

==== Yamagi Quake II Initialized ====

*************************************

[0.0.0.0]:0: client_connect
Loading game...
==== ShutdownGame ====
-------- game initialization -------
LoadLibrary("game.so")
Game is starting up.
Game is baseq2 built on Oct 12 2015.
------------------------------------

------- server initialization ------
80 entities inhibited.
3 teams with 6 entities.
------------------------------------

Server restarted
Server disconnected, reconnecting
Connecting to localhost...
[0.0.0.0]:0: challenge
[0.0.0.0]:0: client_connect



Pumping Station 2
Refusing to download a path with ..: models/monsters/tank/../ctank/skin.pcx
Refusing to download a path with ..: models/monsters/tank/../ctank/pain.pcx
Map: waste3
                                     
pics
                                     
maps/waste3.bsp
                                     
models/weapons/v_blast/tris.md2
                                     
#w_blaster.md2
                                     
#w_shotgun.md2
                                     
#w_sshotgun.md2
                                     
#w_machinegun.md2
                                     
#w_chaingun.md2
                                     
#a_grenades.md2
                                     
#w_glauncher.md2
                                     
#w_rlauncher.md2
                                     
#w_hyperblaster.md2
                                     
#w_railgun.md2
                                     
#w_bfg.md2
                                     
models/objects/gibs/sm_meat/tris.md2
                                     
models/objects/gibs/arm/tris.md2
                                     
models/objects/gibs/bone/tris.md2
                                     
models/objects/gibs/bone2/tris.md2
                                     
models/objects/gibs/chest/tris.md2
                                     
models/objects/gibs/skull/tris.md2
                                     
models/objects/gibs/head2/tris.md2
                                     
models/objects/debris1/tris.md2
                                     
models/objects/debris2/tris.md2
                                     
models/objects/debris3/tris.md2
                                     
models/objects/barrels/tris.md2
                                     
models/deadbods/dude/tris.md2
                                     
models/items/mega_h/tris.md2
                                     
models/items/quaddama/tris.md2
                                     
models/items/armor/body/tris.md2
                                     
models/items/armor/shard/tris.md2
                                     
models/items/healing/medium/tris.md2
                                     
models/items/healing/large/tris.md2
                                     
models/monsters/gladiatr/tris.md2
                                     
models/monsters/soldier/tris.md2
                                     
models/items/ammo/bullets/medium/tris
                                     
models/monsters/float/tris.md2
                                     
models/items/ammo/shells/medium/tris.
                                     
models/items/ammo/rockets/medium/tris
                                     
models/items/healing/stimpack/tris.md
                                     
models/monsters/gunner/tris.md2
                                     
models/items/ammo/cells/medium/tris.m
                                     
models/items/pack/tris.md2
                                     
models/items/keys/key/tris.md2
                                     
models/items/enviro/tris.md2
                                     
models/items/adrenal/tris.md2
                                     
models/monsters/berserk/tris.md2
                                     
models/monsters/tank/tris.md2
                                     
models/items/invulner/tris.md2
                                     
models/weapons/g_bfg/tris.md2
                                     
models/weapons/v_bfg/tris.md2
                                     
sprites/s_bfg1.sp2
                                     
sprites/s_bfg2.sp2
                                     
sprites/s_bfg3.sp2
                                     
images
                                     
client 0
                                     
sky
                                     
]/map mine4.bsp
==== ShutdownGame ====
-------- game initialization -------
LoadLibrary("game.so")
Game is starting up.
Game is baseq2 built on Oct 12 2015.
------------------------------------

------- server initialization ------
********************
ERROR: Couldn't load maps/mine4.bsp.bsp
********************
==== ShutdownGame ====
]/map mine4
-------- game initialization -------
LoadLibrary("game.so")
Game is starting up.
Game is baseq2 built on Oct 12 2015.
------------------------------------

------- server initialization ------
47 entities inhibited.
1 teams with 2 entities.
------------------------------------

[0.0.0.0]:0: client_connect



Lower Mines
Refusing to download a path with ..: models/monsters/tank/../ctank/skin.pcx
Refusing to download a path with ..: models/monsters/tank/../ctank/pain.pcx
Map: mine4
                                     
pics
                                     
maps/mine4.bsp
                                     
models/weapons/v_blast/tris.md2
                                     
#w_blaster.md2
                                     
#w_shotgun.md2
                                     
#w_sshotgun.md2
                                     
#w_machinegun.md2
                                     
#w_chaingun.md2
                                     
#a_grenades.md2
                                     
#w_glauncher.md2
                                     
#w_rlauncher.md2
                                     
#w_hyperblaster.md2
                                     
#w_railgun.md2
                                     
#w_bfg.md2
                                     
models/objects/gibs/sm_meat/tris.md2
                                     
models/objects/gibs/arm/tris.md2
                                     
models/objects/gibs/bone/tris.md2
                                     
models/objects/gibs/bone2/tris.md2
                                     
models/objects/gibs/chest/tris.md2
                                     
models/objects/gibs/skull/tris.md2
                                     
models/objects/gibs/head2/tris.md2
                                     
models/items/healing/large/tris.md2
                                     
models/items/healing/stimpack/tris.md
                                     
models/items/healing/medium/tris.md2
                                     
models/items/ammo/shells/medium/tris.
                                     
models/items/ammo/grenades/medium/tri
                                     
models/weapons/v_handgr/tris.md2
                                     
models/deadbods/dude/tris.md2
                                     
models/items/adrenal/tris.md2
                                     
models/items/ammo/bullets/medium/tris
                                     
models/objects/debris1/tris.md2
                                     
models/objects/debris2/tris.md2
                                     
models/objects/minelite/light2/tris.m
                                     
models/weapons/g_launch/tris.md2
                                     
models/weapons/v_launch/tris.md2
                                     
models/objects/grenade/tris.md2
                                     
models/items/armor/combat/tris.md2
                                     
models/weapons/g_chain/tris.md2
                                     
models/weapons/v_chain/tris.md2
                                     
models/monsters/gunner/tris.md2
                                     
models/monsters/float/tris.md2
                                     
models/weapons/g_rocket/tris.md2
                                     
models/weapons/v_rocket/tris.md2
                                     
models/items/ammo/rockets/medium/tris
                                     
models/objects/rocket/tris.md2
                                     
models/monsters/tank/tris.md2
                                     
images
                                     
client 0
                                     
sky
                                     
]god
godmode ON
]ogg_status
Paused file 5 (music/04.ogg) at 121.92 seconds.

----------- shutting down ----------
==== ShutdownGame ====
Shutting down Ogg Vorbis.
Shutting down OpenAL.
Shutting down input.

**Comment by DanielGibson** [comment] 2015-10-13 14:21
I think this is not the bug. Seems like the game (probably through some triggered entity) wants to play CD track 0 (which is translated to play ogg track "00") - which is a special case for "stop playing music".

**Comment by xDShot** [comment] 2015-10-13 21:31
Isn't it supposed to stop playing music when yo finish all goals on map?

**Comment by Yamagi** [comment] 2015-10-13 21:58
Exactly. That never worked reliable with the original client and most other source ports removed that behavior.

**Closed by Yamagi** 2015-10-13 21:58 UTC

**Comment by maraakate** [comment] 2015-10-13 22:19
The funny thing is the first map in Rogue, you play the level for like 90 seconds and hit a switch and the music stops, though you still have more traversing to do (finding the exit).

**Comment by ewe2** [comment] 2015-10-14 02:26
Ah i see from googling that this is something that has confused people for quite some time, now that I understand I might have a crack at figuring out where this happens, and hopefully make it optional in a patch.

**Comment by maraakate** [comment] 2015-10-14 03:47
I believe it's in the game dll itself for one of the triggers... But you 
could optionally intercept it client side for music changes containing 
track 0 and choose to ignore it.
