### ISSUE TITLE
Background sound bug

### ISSUE THREAD

**Issue by Froyd1** [yquake2/yquake2#675] opened 2021-03-06 01:36 UTC
The other bug is some background sound effects that overlap each other, such as the alarm in game, as it goes off so many times at once in some of the levels. Originally it went off at once, before using the source port. The other problem is with the sound options, it won't let me set it at normal. It keeps setting it back to high in sound quality option. I made a couple of videos of what it sounds like.

What it sounds like when it overlaps repeatably:
https://www.youtube.com/watch?v=A8CrEULwx60

What it supposed to sound like in game:
https://www.youtube.com/watch?v=rRMh_NmMMUw

**Comment by Yamagi** [comment] 2021-03-06 16:25
Hmm... I never noticed that. In the video it's clearly to hear that something is wrong. I'll look into it. But I can't promise that this is a fixable problem.

Quake II makes a lot of assumptions in regard of sound timings. There are these fishy timestamp calculations between the game and the client. Once the client started asound, there's no further synchronization. That worked more or less with the native sound system and Windows 98. With YQ2 and it rather precise internal timing, OpenAL and those fancy modern sound card drivers, things become hairy. The normal short sounds like gunshots, monsters, etc. play correctly. But longer sound may get slighty out of sync.

And all that may take a few days. I'm short on time and the whole Covid mess doesn't make things better.

**Comment by Froyd1** [comment] 2021-03-06 18:40
Thanks for your response and take your time to fix this issue. I tested this on Vulkan Q2 port and didn't have this issue. Also the sound options in the main menu are different too in Vulkan.

**Comment by Yamagi** [comment] 2021-03-11 07:35
Okay, I had a deeper look. I'm still not convinced if this is a bug or just a side effect of OpenAL. YQ2 has two sound system:

* There's the classic sound system, which is one way or the other used by most source ports. It can be selected by `s_openal 0` followed by a `snd_restart`. The classic sound system does the stereo spartialization, generates a sound sample stream and paints it through SDL. Since SDLs support for Pulseaudio and the like is limited, it might not work on modern Linux systems.
* And there's OpenAL, which takes the raw samples from Q2 and does all the complicated stuff like spartialization and painting by itself. Since the results are much better when compared to the classic sound system, OpenAL has support for full surround sound and is much more compatible with modern Linux distributions and Win 10, OpenAL is the default.

With the classic sound system the alarm sirens are a little bit louder and their sound field is wider, they can be heard at a greater distance compared to OpenAL. That can be mitigated by pumping up the spartialization parameters of loop sound for OpenAL in openal.c line 490. We won't do that globally, because OpenALs spartializations are much more precise than the rather simple and speed optimized spartialization code of the classic sound system.

With OpenAL it's rather obvious that the alarm sirens start synchronized and desychronize  within the first 60 second. With the classic sound system that's hard to say, because their sound fields are overlapping much more. I think they don't. Which is strange, because the code is nearly the same. The samples are started, as soon as the 'start sound' event is read from the server. I'll ask @DanielGibson if he can have a look. He write the OpenAL backend and has much more OpenAL experience.

**Comment by Froyd1** [comment] 2021-03-11 15:55
Why not add both options in the main menu of the game? So you can select what's suitable for yourself.

**Comment by j4reporting** [comment] 2021-03-11 17:43
IMHO there is no need to put every single option into some kind of menu.  Let's keep it simple. There is a reason for the console and all available options and commands are documented.  :)

**Comment by Yamagi** [comment] 2021-03-11 18:21
Yeah, the menu is for the most common options, relevant to all player. For everything else there's the console. Most cvars have a sane default and it's usually not necessary or even a good idea to change them. The sound system is a good example. The classic sound system is still there, because the code exists. But OpenAL is the better choice for nearly all cases. I'm not even sure if the classic sound system works on Windows 10.

As I said, we'll try to figure out why the sound gets out of sync and try to work around that if it is possible. But one must keep in mind, that Quake II was released in 1997. Even though the game has aged better than many other 1990th games, it was never meant to run on todays hardware. It has architectural limitations and  the game data is build with a Pentium 90 rendering the game in software in mind. With the OpenGL 3.2 and Vulkan renderers, precise timings for modern LCDs, surround sound support and so on we already pushed the code to or even beyond it's limits. Some small divergences from Vanilla Quake II are the price to be paid for that.

**Comment by Froyd1** [comment] 2021-03-11 18:34
> 
> 
> IMHO there is no need to put every single option into some kind of menu. Let's keep it simple. There is a reason for the console and all available options and commands are documented. :)

Oh okay. :)

> 
> 
> Yeah, the menu is for the most common options, relevant to all player. For everything else there's the console. Most cvars have a sane default and it's usually not necessary or even a good idea to change them. The sound system is a good example. The classic sound system is still there, because the code exists. But OpenAL is the better choice for nearly all cases. I'm not even sure if the classic sound system works on Windows 10.
> 
> As I said, we'll try to figure out why the sound gets out of sync and try to work around that if it is possible. But one must keep in mind, that Quake II was released in 1997. Even though the game has aged better than many other 1990th games, it was never meant to run on todays hardware. It has architectural limitations and the game data is build with a Pentium 90 rendering the game in software in mind. With the OpenGL 3.2 and Vulkan renderers, precise timings for modern LCDs, surround sound support and so on we already pushed the code to or even beyond it's limits. Some small divergences from Vanilla Quake II are the price to be paid for that.

I see what your saying there, and that sounds complicated. Hopefully you can fix this issue of why the background sounds go out of sync, because I never had this problem before. I will wait patiently for the fix.

**Comment by j4reporting** [comment] 2021-03-11 20:25
> I'm not even sure if the classic sound system works on Windows 10.
It still works on Windows 10.  

Does 'lower palace' have several sources for this alarm sound? It seems I can't reproduce it on other maps ( i.e. Detention Center), where  the enemies are pushing an alarm button and the area where the alarm is played is quite small.

In 'lower palace' the bug is only triggered if you move around. Just standing still won"t add any new alarm sound. Then you can hear the different loops coming from several directions, while with classic sound it's more like MONO. Also just bringing down the console or pausing the game stops the overlapping alarm sounds.

Ah,  I can also reproduce it in 'Detention Center' ( blue key ) but only at a certain spot outside near the wall, There two alarm sources might overlap. It's much harder to trigger the overlapping sounds near the alarm button.


![q2_detention_center](https://user-images.githubusercontent.com/45177907/110850540-2e71d880-82b0-11eb-8e51-4783678254f9.png)

**Comment by Yamagi** [comment] 2021-03-11 21:18
Jepp, these are different sound targets. I'm still not sure if they should be synchronized. Or if they aren't synchronized and the different / diverging start times are the normal behavior which is not audible with the classic sound system. The Detention Center is a good tip, having more than one place to reproduce is always good.

**Comment by BjossiAlfreds** [comment] 2021-03-13 20:22
Can reproduce this with my own gamex86 based on the original game source, Q2 plays it mono but YQ2 does the overlaps.

I can provide more insight into this based on in-game observation. The original client merges redundant sound events, that is why you hear the siren as a mono sound, the other sound events aren't being played at all.

You can also hear this with a group of flyers. You only hear the flying sound from one of them in the original client, the others are silent, while in YQ2 all of them play their flying sound.

In fact the original client is really aggressive with this. Even if I stop hearing the flyer sound completely, the other flyer that I'm close to is still silent because the game thinks it is redundant due to the more distant flyer.

I can see a few possibilities:
1. Original client also messes up the timings but we never notice it because the other sound events are silenced due to this merging mechanism.

2. The YQ2 client has the same merging mechanism and it works as intended but the timings are different so the game thinks the sound events aren't redundant and thus don't get merged.

**Comment by Yamagi** [comment] 2021-03-15 16:48
I think I got it. This is not a bug: Loop sounds aren't send to the client as sound start events, they're connected to the entities known by the client. The magic is in `S_BuildSoundList()`. Both Openal and the classic sound system call that function to get a list of all entities in the current frame. If an entity has a sound associated with it, it's checked whether that sound is already played. If not, playback is started.

The Quake II sound system thinks in "channels", each sample is connected to a channel and each channel has a well defined start and stop time. When starting playback, a new channel is allocated, the sample is uploaded into it and it's end time is set to current time + sample length. From that point the channel plays from the samples start to end, after it has reached the samples end the channel is deallocated.

So the normal lifecycle of a looping sound like the klaxon1.wav in city.bsp is entity get's known by the client -> playback of the sample is started by allocating a channel -> as long as that channels exists nothing happens -> but when the sample has reached it's end, the channel is deallocated -> if the entity is still known to the client, the sample is started again in the next frame.

Now the problem is, that never all entities in map are known to client. Instead only entities of all active areas and some special entities are known. This has two consequences.

1. If a long a samples is started, it's played to it's end. Regardless if the player is still near it's source or not. This is why using samples longer than a few seconds is usually a bad idea. Neither baseq2 not the addons did that.
2. If the player moves from one area to another, for some time both areas are active. They can hear all entity sounds in the old area until that area is getting inactive and the samples have played to their end. And they can here all entity sounds in the new area.

This is case 2. The klaxons in the old area are played relative to the moment the player entered the area, the klaxons in the new area relative to the moment the player entered it, etc. The player taharts at that blaster trap, runs over the balcony and into the staircase. They cross three areas and here (for at least a short time) three klaxons with three different start dates.

With OpenAL it's much better to hear, because - as @BjossiAlfreds pointed out - the classic sound system merged redundant samples. The klaxons have a high probability to cancel each other out.

**Comment by Froyd1** [comment] 2021-03-19 19:11
How's progress coming along with this issue? I've been playing the game in classic sound system, as I followed how to manually change it in the config.cfg file from `s_openal 1` to `s_openal 0`.

**Comment by Yamagi** [comment] 2021-03-20 15:35
See my comment above. This isn't a bug and cannot be fixed: The sound entities start playing as soon as they get known to the client. As the player moved through the different areas of the map, sound entities appear and disappear. In city2.bsp the klaxons are in different areas. With the classic sound system they mostly cancel each other out, which mitigates the problem. OpenAL positions ans spartializes them correctly.

**Closed by Yamagi** 2021-03-20 15:35 UTC
Labels: bug

**Comment by Froyd1** [comment] 2021-03-20 17:17
I'm sorry, I found the above comment too confusing. That's too bad it can't be fixed, thanks for the explanation and for trying to fix this.
