### ISSUE TITLE
Missing one enemy in the following levels of The Reckoning

### ISSUE THREAD

**Issue by Froyd1** [yquake2/yquake2#682] opened 2021-03-23 18:11 UTC
Been playing through The Reckoning on medium difficulty, and I have scoured the levels over and over again and I can't find the enemy. My guess its just an enemy who fails to spawn on a surprise attack or something, but man is it frustrating. One enemy is missing in these levels listed below:

UNIT 3

Industrial Facility 

Kills 54/55

![20210323105129_1](https://user-images.githubusercontent.com/80136749/112195385-20cd2480-8bc7-11eb-9bac-a132c4e39a23.jpg)

Water Treatment Plant 

Kills 53/54

![20210323104733_1](https://user-images.githubusercontent.com/80136749/112195435-317d9a80-8bc7-11eb-9994-375912d13604.jpg)

**Comment by BjossiAlfreds** [comment] 2021-03-28 15:25
The one in Water Treatment Plant is a triggered spawn without a targetname. Not sure about the one in Industrial Facility yet, might be a triggered spawn with a targetname that is never targeted. Could you run the listentities command in your save and tell me the classname and co-ords?

**Comment by Froyd1** [comment] 2021-03-28 16:12
I ran the "listentities monsters" command in the level Industrial Facility, and it came up like this in the console. I don't know which monster is missing? Maybe this screenshot will help?

![20210328090514_1](https://user-images.githubusercontent.com/80136749/112758840-2d75c200-8fa5-11eb-8b6f-4f914c84bb65.jpg)

**Comment by BjossiAlfreds** [comment] 2021-03-28 16:18
Oh right, those are probably dead bodies. Unfortunately the command has no filtering ability, so you'll have to gib the bodies to narrow the list down to the culprit.

**Comment by Yamagi** [comment] 2021-03-28 16:33
> Oh right, those are probably dead bodies.

They're. Maybe we should change `listentities monster` to list only monsters with health >0 and add a new command `listentities allmonsters` or something like that.

**Comment by BjossiAlfreds** [comment] 2021-03-28 17:34
That sounds good to me.

**Comment by Froyd1** [comment] 2021-03-28 18:12
> 
> 
> Oh right, those are probably dead bodies. Unfortunately the command has no filtering ability, so you'll have to gib the bodies to narrow the list down to the culprit.

Okay I narrowed it down to one in Industrial Facility.

`monster_gunner:  464.000000 2009.000000  152.031250`

The other one in Water Treatment Plant.

`monster_soldier_hypergun: -1224.000000 -1472.000000 280.000000`

**Comment by BjossiAlfreds** [comment] 2021-03-28 18:31
The hypergun guy is triggered spawn but has no targetname. The gunner guy is also trriggered spawn and does have targetname t238 but there is no entity that triggers it.

While it is possible to write a routine that does a deep scan of target-targetname linkage, it would be very complicated due to how different entities fire their targets, at least if we want it to be thorough. Probably the best fix would be an updated entlist or a map hack in code.

**Comment by BjossiAlfreds** [comment] 2021-03-29 22:50
Here are fixed entity strings for these maps. I made the gunner in Industrial Facility surprise you once you go up the elevator after picking up the green key, and the hyperblaster soldier joins the other two in fighting you, so they all 3 have targetname t70 which is what I guess was intended originally.
[xatrixfixes.zip](https://github.com/yquake2/yquake2/files/6224989/xatrixfixes.zip)

**Comment by Froyd1** [comment] 2021-03-30 04:32
Thanks again for the small patch! Can confirm, you can now get a 100% kills in those levels! :D

**Comment by Yamagi** [comment] 2021-04-08 09:08
I've merged the entity files into the xatrix repo.

**Closed by Yamagi** 2021-04-08 09:08 UTC
Labels: bug
