### ISSUE TITLE
Windows: issues with included OpenAL32.dll when exiting  yquake2

### ISSUE THREAD

**Issue by j4reporting** [yquake2/yquake2#628] opened 2020-11-24 19:09 UTC
While testing the current vulkan renderer on windows 10,  I saw another issue that is also present in latest release.
Apparently exiting yquake2 takes very long time to unload from system. Screen  closes immediately, but the dos box created by starting vulkan yquake binary with a batch file  remained active for several seconds (system 1).  On system 2  I even got a crash every time, with no usefull info. The only hint in event viewer is a reference to OpenAL32.dll.

Using the latest version of OpenAL32.dll fixes this on both systems.

both systems run Win10 (1909)  with Skylake CPUs, Intel GFX driver  27.20.100.8681 / Intel display audio  driver 10.26.0.9
systen 1:   NUC    iGPU Iris Graphics 540 , external display / audio device  Intel Display audio
system 2:  laptop  iGPU HD Graphics 530,   internal display  / audio device:  Realtek HD Audio

**Comment by Yamagi** [comment] 2020-11-25 12:49
Hmm... An audio problem and Intel GPUs. This could be another instance of Intels inability to write a GPU driver that doesn't mess with the sound system. @DanielGibson can you give it a try on your Brix?

**Comment by some0nebad** [comment] 2020-11-25 15:19
I can confirm this issue on Windows 10 2004 on AMD RX460. But I can't reproduce it on Windows 7

**Comment by DanielGibson** [comment] 2020-11-25 15:34
There was a bug in openal-soft 1.20 on windows (when built with  mingw, as their official release is) - it crashed when exiting the program (something about global destructors not being called in the right order or sth).
It should be fixed in 1.21 which was released 3 weeks ago - and apparently it is:

> Using the latest version of OpenAL32.dll fixes this on both systems.

I think we don't have to do anything besides bundling an updating openal32.dll in the next release

**Comment by DanielGibson** [comment] 2020-11-25 15:46
see also https://github.com/dhewm/dhewm3/issues/303#issuecomment-668028589

**Comment by Yamagi** [comment] 2020-11-27 10:34
I've uploaded an updated version of the 7.45 release and added a note to the homepage: https://deponie.yamagi.org/quake2/windows/quake2-7.45a.zip The binaries are the same, I've just replaced the openal32.dll with 1.21.

**Closed by Yamagi** 2020-11-27 10:34 UTC
