### ISSUE TITLE
[Bug] vid_restart changes particle shape

### ISSUE THREAD

**Issue by OpenRift412** [yquake2/yquake2#805] opened 2022-03-21 00:21 UTC
Noticed this weird little bug today that causes circular particles to become square when switching 'games' with the `game` console command. Issue doesn't seem to happen when loading it through the command line with the `-game` parameter.

**Comment by Yamagi** [comment] 2022-03-26 15:51
That's likely caused by the fragile reexecution of config files when changing the game. Quake II cannot remove cvars once they're known to the game, it just can reset them to other values. That has some interesting side effect. Two and a half questions questions to be able to reproduce this:

* With what renderer do you see the problem?
* Has the game you're changing to already a config file?
* if it has, does changing the game change the renderer? Do you have different renderers configured for the games?

**Comment by OpenRift412** [comment] 2022-03-26 21:11
> That's likely caused by the fragile reexecution of config files when changing the game. Quake II cannot remove cvars once they're known to the game, it just can reset them to other values. That has some interesting side effect. Two and a half questions questions to be able to reproduce this:
> 
> * With what renderer do you see the problem?
> * Has the game you're changing to already a config file?
> * if it has, does changing the game change the renderer? Do you have different renderers configured for the games?

Upon further inspection, it actually seems to be that every time a vid_restart is triggered, that's what causes the particle shape change. I suspect it may have to do with `r_2D_unfiltered` also "unfiltering" particles as well.

They all have the same renderer (OpenGL 1.4), and yes they do have a config file. I checked the particle settings via the console vars and the settings all have square particles disabled. Changing it to square particles and then back to circular particles seems to fix it, though.

**Comment by Yamagi** [comment] 2022-03-27 10:06
@DanielGibson found a bug with `r_2D_unfiltered` in GL1. It's fixed in this testbuild: https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-20220327-f738eb.zip Can you give it a try and see if the problem still persists?

**Comment by OpenRift412** [comment] 2022-03-27 15:56
> @DanielGibson found a bug with `r_2D_unfiltered` in GL1. It's fixed in this testbuild: https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-20220327-f738eb.zip Can you give it a try and see if the problem still persists?

Yeah, the problem still persists, it seems.

**Comment by Yamagi** [comment] 2022-03-29 06:07
Found it. In https://github.com/yquake2/yquake2/blob/master/src/client/refresh/gl1/gl1_main.c#L1671-L1689= `GL_POINT_SMOOTH` is set only if `gl1_particle_square` is modified. That is the case right after the game was started, since the config parser read the cvar from the config and marked it as modified. After an `vid_restart` it's unmodified, thus the code is never executed.

**Comment by OpenRift412** [comment] 2022-03-29 16:54
> Found it. In https://github.com/yquake2/yquake2/blob/master/src/client/refresh/gl1/gl1_main.c#L1671-L1689= `GL_POINT_SMOOTH` is set only if `gl1_particle_square` is modified. That is the case right after the game was started, since the config parser read the cvar from the config and marked it as modified. After an `vid_restart` it's unmodified, thus the code is never executed.

Awesome, good to hear.

**Comment by DanielGibson** [comment] 2022-03-29 17:18
> GL_POINT_SMOOTH is set only if gl1_particle_square is modified.

and on the other hand, the particle texture is only updated (via `R_InitParticleTexture()`) if pointparameters are available - which (as far as I can tell) makes zero sense, as the texture is only used if pointparameters are *not* available (or not enabled)

**Closed** 2022-03-29 18:30 UTC
Labels: bug, question

**Comment by Yamagi** [comment] 2022-03-29 18:38
This was quite successful. Fixed the reported bug, an unrelated problem with the unfiltered 2D stuff and figured out that on Ampere GPUs `GL_POINT_SMOOTH` is always enabled. The driver ignores everything else. I'll build another set of Windows binaries tomorrow or so.

**Comment by Yamagi** [comment] 2022-04-03 16:01
This took longer than expected: https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-20220403-9d451fa.zip

**Comment by OpenRift412** [comment] 2022-04-03 18:43
> This took longer than expected: https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-20220403-9d451fa.zip

Gave it a test, works great!
