### ISSUE TITLE
Linux: v5.3.1 feature request: console access in-game

### ISSUE THREAD

**Issue by ewe2** [yquake2/yquake2#93] opened 2015-10-11 13:18 UTC
The console access (~) doesn't work in-game unless you go to options and access it from there. Would just be handy.

**Comment by DanielGibson** [comment] 2015-10-11 13:23
I think if ~ works depends on your keyboardlayout, but shift+escape 
should always work.

**Comment by ewe2** [comment] 2015-10-11 13:37
~ is bound to "toggleconsole" but doesn't work and I've never had that issue before but shift+esc does work so I'll have to remember that I guess!

**Comment by DanielGibson** [comment] 2015-10-11 13:38
what keyboard layout do you use?

**Comment by ewe2** [comment] 2015-10-11 13:43
Standard windows one, using a Logitech USB keyboard.

**Comment by DanielGibson** [comment] 2015-10-11 13:46
I thought you were using Linux?

But what I'm really asking about is, if this is the standard US layout, 
UK, German, ...
And where is that ~ button? between Esc, Tab and 1?

**Comment by ewe2** [comment] 2015-10-11 13:57
Sorry, standard US layout and the ~ key is in the standard place, on the left of 1 below Esc and above Tab. I said windows to indicate it has a windows key (104-key layout).

**Comment by DanielGibson** [comment] 2015-10-11 13:59
Ok, I think that should work.. will look into it.

(Meanwhile Shift+Esc should do the trick ;))

**Comment by DanielGibson** [comment] 2015-10-11 14:37
hmm the code looks like it should work with `~` ..

do you use dead keys or not? i.e. if you press `^` and then `e` (in the terminal or a text editor), do you get "^e" or "ê"?

**Comment by xDShot** [comment] 2015-10-11 16:36
Same for me on Linux. The console doesn't open when I press ~ button in game with US layout. With RU layout it opens, though.

**Comment by ewe2** [comment] 2015-10-11 20:27
I use the windows key as a compose key specifically to avoid that. If it helps, the ~ key works perfectly fine in the older quake engine and updated doom engines, so I'm wondering if it isn't an SDL2 thing, since I've rarely used it?

**Comment by deuxsonic** [comment] 2015-10-12 10:08
I found that by binding the console to ` instead of ~ it gets rid of this problem. I noticed this as well. Hopefully this helps.

**Comment by ewe2** [comment] 2015-10-12 10:30
Well the odd thing is that backtick (`) is also bound to toggleconsole but this has no effect either. It just seems like it doesn't like the key.

**Comment by mackron** [comment] 2015-10-15 00:23
I had a look into this, and the issue is that Con_ToggleConsole_f() is getting called in cl_keyboard.c in response to a hard-coded key binding (line 956), but then it's getting called immediately after in response to "toggleconsole". So it's getting toggled on, and then immediately toggled off again thus appearing to have no effect.

A quick fix is to remove the hard coded key bindings in cl_keyboard.c, but I'm not familiar with the code base so I'm not sure if that's the best way of doing it.

Alternatively, removing the ` and ~ bindings from your config also works for me.

**Comment by ewe2** [comment] 2015-10-15 00:26
Sounds like a cvar needs rescuing!

**Comment by ewe2** [comment] 2015-10-15 01:39
I've looked at the code and half of it seems to be a left-over from the original handling and I'm unsure why shift+esc was put there instead unless its a layout hack. But there is no reason to hard-bind "~" and "`" anyway. I will try a few different things, the main idea will be to make toggleconsole work for those keys again.

**Comment by DanielGibson** [comment] 2015-10-15 01:56
One thing to keep in mind is that keys that actually produce chars (or edit them presumably, like backspace, enter, del, ..) need special handling when you wanna close the console with them, otherwise you'll just get the char.
So `bind F10 toggleconsole` just works, but `bind t toggleconsole` not so much - you can open the console with `t` then, but not close it again.
I think that's what `consolekeys[]` is for and it's why we do
```
	consolekeys['`'] = false;
	consolekeys['~'] = false;
	consolekeys['^'] = false;
```

**Comment by ewe2** [comment] 2015-10-15 03:25
Then perhaps we just remove toggleconsole since it is actually useless and only confuses people.

**Closed** 2015-10-15 15:54 UTC

**Comment by DanielGibson** [comment] 2015-10-15 15:55
instead of removing toggleconsole I removed the ability to bind the standard console keys (and Escape, because you shouldn't bind that either)

can you confirm that it works for you, too?

**Comment by deuxsonic** [comment] 2015-10-15 16:16
I would but I've never built the binaries before (I use Windows). If you do then I can verify that it works.

Ryan 


     On Thursday, October 15, 2015 11:55 AM, Daniel Gibson <notifications@github.com> wrote:
   

 instead of removing toggleconsole I removed the ability to bind the standard console keys (and Escape, because you shouldn't bind that either)can you confirm that it works for you, too?—

**Comment by ewe2** [comment] 2015-10-15 21:19
That works fine, tested binding in the console with it. Still figuring out how to make those keys work, though. I've got them half-working but you still end up with the key registering on the console commandline instead of merely toggling.

**Comment by DanielGibson** [comment] 2015-10-15 22:03
that's strange, for me the console is clear after pressing any of ^, ~ or `.
are you using SDL2?

@deuxsonic I don't currently have time to create windows builds for testing, maybe another day :-/

**Comment by ewe2** [comment] 2015-10-15 22:15
Yeah I'm using SDL2, this is code I'm working on in a topic branch, adding `/~^ to the shift+esc logic, and it's a bit odd that this is happening. I'm still mystified as to why the key doesn't work for me at all without doing this.

**Comment by DanielGibson** [comment] 2015-10-15 22:17
have you tried my latest code in  master?

**Comment by ewe2** [comment] 2015-10-15 22:22
Oh my apologies! I was on the wrong branch at the time when i did testing, yes it finally works, so I can forget that topic branch :D

**Comment by Yamagi** [comment] 2015-10-16 08:03
New windows binaries can be found here: http://deponie.yamagi.org/quake2/windows/quake2-5.32pre1.zip

**Comment by deuxsonic** [comment] 2015-10-16 09:33
The new binaries break the cinematics. When you start a new game for example, a few frames will play and then will stop and load the level as if a key was pressed. 


     On Friday, October 16, 2015 4:03 AM, Yamagi <notifications@github.com> wrote:
   

 New windows binaries can be found here: http://deponie.yamagi.org/quake2/windows/quake2-5.32pre1.zip—

**Comment by deuxsonic** [comment] 2015-10-16 09:37
The console button does still work. Not sure how the changes have messed up the cinematics though.

**Comment by DanielGibson** [comment] 2015-10-16 12:09
On 10/16/2015 11:33 AM, Ryan wrote:
> The new binaries break the cinematics. When you start a new game for
> example, a few frames will play and then will stop and load the level as
> if a key was pressed.
>

Strange, this doesn't happen for me (with the same Windows binaries).

**Comment by deuxsonic** [comment] 2015-10-16 12:21
I ended up changing my post after I dug deeper. If you bring the console down and interrupt the id cinematic and then start a new game, the intro cinematic will be interrupted by a seemingly phantom keypress.
 


     On Friday, October 16, 2015 8:09 AM, Daniel Gibson <notifications@github.com> wrote:
   

 On 10/16/2015 11:33 AM, Ryan wrote:
> The new binaries break the cinematics. When you start a new game for
> example, a few frames will play and then will stop and load the level as
> if a key was pressed.
>

Strange, this doesn't happen for me (with the same Windows binaries).
