### ISSUE TITLE
Shift+6 brings up the console, interfering with gameplay

### ISSUE THREAD

**Issue by kinkock** [yquake2/yquake2#616] opened 2020-10-10 16:07 UTC
pressing shift+6 brings up the console, which interferes with game-play when shift is being used.

~~edit: this bug is directly connected to quake 2 vanilla though still needs fixing due to serious game-play issues it introduces.~~ I did not experience it with quake 2 vanilla, I actually failed to uninstall the source-port.

**Comment by Yamagi** [comment] 2020-10-11 07:20
What keyboard layout do you have?

**Comment by kinkock** [comment] 2020-10-11 23:57
A US keyboard

**Comment by DanielGibson** [comment] 2020-10-12 02:46
Shift-6 on US-QWERTY is `^` - which is the char of the "console key" (between Tab, Esc and 1) on German keyboards, so I guess we have that hardcoded somewhere.
This shouldn't be necessary anymore, as we detect the "console key" by scancode (`SDL_SCANCODE_GRAVE`) and generate the `K_CONSOLE` pseudo-key on those cases that always opens/closes the console.

**Comment by Yamagi** [comment] 2020-10-31 15:59
I'm unable to reproduce this with a clean config and I didn't find a place were `^` is still hard coded. Do you have an old config with `^` still bound to `toggleconsole`?

**Comment by Yamagi** [comment] 2020-11-14 16:45
No answer for 14 days, closing here. If it's still an issue feel free to reopen the issue.

**Closed by Yamagi** 2020-11-14 16:45 UTC
