### ISSUE TITLE
models (enemy, items) brightness

### ISSUE THREAD

**Issue by crmb** [yquake2/yquake2#54] opened 2014-11-30 21:09 UTC
This is about the Windows pre-compiled binaries 5.23 (Win7 x64 + Geforce)

3D models (player hand, items & enemy) seems to be not gamma corrected

i checked with vanilla 3.20 (with the broken dark picture), look at the heath items, or player hand on below screenshots :
with 3.2 the lightning is consistent, with yquake2 the models are too dark

![3 20_1](https://cloud.githubusercontent.com/assets/10013125/5239581/f614d76e-78e6-11e4-801e-9dd1c906af16.jpg)
![yq2_1](https://cloud.githubusercontent.com/assets/10013125/5239582/f641f1e0-78e6-11e4-929f-70b7ffe0435e.jpg)
![3 20_2](https://cloud.githubusercontent.com/assets/10013125/5239502/40a3b49c-78e4-11e4-9990-8cab9ac388b3.jpg)
![yq2_2](https://cloud.githubusercontent.com/assets/10013125/5239501/40a2d3f6-78e4-11e4-9ad7-b62d457eb3cc.jpg)

**Comment by Yamagi** [comment] 2015-01-03 09:53
That's a nice find. I wonder why this is only seen on Windows and not on Linux or even FreeBSD. Maybe some kind of driver issue on either side. Nevertheless, not only models are too dark but all dynamic lights. Can you try to set gl_modulate to the same value as vid_gamma? That should solve / work around the problem.

Regarding new builds: I planed to release 3.24 in December but had no time. I'll try it again at the end of January. :) But it'll only be another bugfix release without new features. The biggest changes are
* The HUD scale stuff is now working as expected, the menu and console can be scaled too. 
* Some progress stoppers when playing 'rogue' in coop with friendly fire of were fixed. 
* The underwater sound now works with the SDL backend.

**Comment by deuxsonic** [comment] 2015-01-03 13:28
I can't wait.

**Comment by crmb** [comment] 2015-01-04 02:50
Hello !

Yes gl_modulate around 1.5 (default seems to be 1 like vid_gamma) kind of solve the problem but it also make wall/floor textures brighter (after a vid_restart) so i am not sure if the picture is right.

if you plan to release a new build :

- I think the game doesnt start if you don't have the openal dll (even with openal set off in the cfg)
- I have tried a bit openal but the stereo was weird for me. If i shoot parallel to a wall, the sound effect will come from the wall side. I guess this is supposed to be reverberation but this is much too pronounced and unnatural.
- I am an french azerty layout user. To type number we are supposed to use SHIFT+Key. But in yamagi quake i can only type number (even without pressing SHIFT), and thus, i can not type characters like _

Thanks ! It is my fav client for quake 2, good companion to QuakeSpasm

**Comment by deuxsonic** [comment] 2015-01-04 21:08
That's why I thought the HUD/menu/UI scaling was a good idea for the port -- it is faithful to the original game but modernizes it, fixing bugs, and already has support for music files and QuakeSpasm is basically perfect for the original Quake, having all of these things plus the fullbrights fix that FitzQuake had, so it's a matter of waiting for YQ2 to get another release to have the stuff added since I don't feel confident in my ability to compile it all myself. Then I'll have what I feel are ideal ports of Quake 1 and Quake 2.

**Comment by Yamagi** [comment] 2015-01-18 17:19
Okay:

  * Most longstanding keyboard layout issues should be fixed by last 3 commits. We're now using char events for the console and chat windows which are decoded by SDL into the current locale. But Quake II is still limited to the 127 basic ASCII characters and that'll never change. 
  * Regarding OpenAL: Quake II doesn't use any reverb effects besides the underwater effect. But OpenALs calculations are very limited by the available data which has some unwanted side effects. For example all sound calculations are done in 2D coordinates.
  * Being unable to start the game without openal32.dll may be a side effect of our broken linkage on Windows. That's pretty high on the todo list, together with switching back to a dynamic SDL20.dll.
  * So far I haven't found the cause of models being too dark on Windows.
  * The save game path to "My Documents" is hardcoded and can be changed by recompiling the source only.

**Comment by deuxsonic** [comment] 2015-06-08 16:17
Another new release coming anytime soon?

**Comment by mackron** [comment] 2015-10-22 03:44
I had a look into this one and I've found what's causing it - it's not so much that the models are too dark, but rather the lights on the walls are too bright. The issue comes down to the use of GL_ARB/EXT_texture_env_combine which is controlled with the "gl_ext_mtexcombine" cvar. More specifically, however, it's actually "gl_overbrightbits" that's causing it. When the light map is combined with the wall texture, a scaling factor of "gl_overbrightbits" is applied using the GL_RGB_SCALE_EXT texture environment parameter. That same scaling factor is not applied to models which results in the inconsistent brightness. It appears "gl_overbrightbits" is set to "2" by default.

To fix this I would personally just remove "gl_ext_mtexcombine", "gl_overbrightbits" and the GL_ARB/EXT_texture_env_combine branch because I'm not really seeing the point in it... but I'm assuming they were added for a reason so maybe it's not necessarily the best way. But if indeed this is the approach you would prefer, I can make the changes and do a pull request since it's fresh in my mind at the moment.

A temporary fix is to either change your config such that "gl_overbrightbits" is set to "1" (set to "2" by default) or "gl_ext_mtexcombine" is set to "0" (set to "1" by default).

The relevant rendering code is on lines 991 and 1224 in r_surf.c.

**Comment by deuxsonic** [comment] 2015-10-22 04:05
I actually like the lighting and overbrights in YQ2 as it looks much improved from vanilla Quake 2.

**Comment by deuxsonic** [comment] 2015-10-22 04:16
One of the things that made GLQuake inferior to the software-rendered original was the loss of overbrights which made the game look very bland. A number of Quake source ports like QuakeSpasm, the one I use, fix this issue. Vanilla Quake 2 has this same problem so I was pleasantly surprised to find that YQ2 properly handles things that should be overbrights, like light bulbs, plus the whole game's lighting is much brighter and more colorful than vanilla Quake 2, so I don't suggest making changes to YQ2's environment lighting. I would take pickups that appear too dark over losing the lighting. For things like medkits that strobe, at the peak of their strobe they're actually at what would be the proper base brightness so perhaps something can target those, but honestly I feel it's not all that noticable.

**Comment by mackron** [comment] 2015-10-22 05:11
Yeah I don't particularly care personally - I'll just adjust my config. Still, applying a brightness setting to walls, but not models feels like a strange way of doing it in my opinion.

Applying "gl_overbrightbits" to models is another way to address it, but I'm not sure how one would go about it.

**Comment by deuxsonic** [comment] 2015-10-22 05:23
The strange part is that it actually isn't all that noticable for me if it's a problem for me at all. Perhaps there's something different about our configs or systems that's causing it?

**Comment by deuxsonic** [comment] 2015-10-22 05:31
![1](https://cloud.githubusercontent.com/assets/7662909/10657625/3fec3718-785c-11e5-9ebb-5e7524f3be2c.JPG)
![2](https://cloud.githubusercontent.com/assets/7662909/10657626/42b7bd50-785c-11e5-9bc7-341594bcee40.JPG)
![3](https://cloud.githubusercontent.com/assets/7662909/10657627/45050f36-785c-11e5-9fca-d2e688625a33.JPG)
Here are pictures of the same spots taken by crmb. Perhaps it's just me, but everything seems to be pretty much the right brightness, matching up to their surroundings (since pickups strobe, I took them at their lowst point in the strobe)?

**Comment by mackron** [comment] 2015-10-22 05:38
If you drop down the console and toggle between "set gl_overbrightbits "2"" and "set gl_overbrightbits "1"" it becomes more obvious - you can see how the walls change brightness but not the regular meshes. Also, gl_overbrightbits has no effect if gl_ext_mtexcombine is set to 0.

I have figured out how to apply gl_overbrightbits to regular meshes. Here are some screens that might show off the effect more clearly. Note that the health pack is at it's dimmest point in it's strobe cycle in both screens.

![yquake2_bug_1](https://cloud.githubusercontent.com/assets/1232553/10657696/b650f530-78d2-11e5-8faf-c99b8e4943d0.png)
![yquake2_bug_0](https://cloud.githubusercontent.com/assets/1232553/10657699/be1e3d90-78d2-11e5-89e1-94afddb2c8c6.png)

**Comment by deuxsonic** [comment] 2015-10-22 05:41
Awesome. Can you share your fix? You wouldn't happen to be able to fix with issue #87 as well would you?

**Comment by Yamagi** [comment] 2015-10-22 05:45
That's a very nice find. I was tinkering with closing this issue because I was unable to find what causes it. I think it's much more visible on Windows with Nvidia cards than on Linux or FreeBSD, but that may be my imagination.

The overbright bits patch was a small patchset used by many player back in 2008 when I started with YQ2. So I applied it to my sources. Removing it would be one option, but as Ryan said.It's nice to have. The other way round (applying overbright bits to models) would be better, but I must admit that my OpenGL foo and my understanding of the Quake II renderer (models are handled somewhat differently as the the world) is somewhat limited. So it would be really nice of you can share your changes, even if they're hacky. :)

**Comment by mackron** [comment] 2015-10-22 05:49
Yep, I'll organize a pull request in a bit. I tested on both my onboard Intel and Nvidia GPUs and the effect was the same.

Will take a look at #87.

**Comment by Yamagi** [comment] 2015-10-22 05:58
#87 would be awesome. It shouldn't be too hard.

**Comment by deuxsonic** [comment] 2015-10-22 06:01
Yes, that's really the only remaining issue I have. Other ports like AprQ2, the R1GL renderer from the R1Q2 port, and DirectQII have nailed the solution, generally with only a single CVAR that needs to be changed.

**Comment by deuxsonic** [comment] 2015-10-22 07:44
Nice job. I manually added your code to see what it looks like in-game and now I can see it makes a huge difference.

Hopefully you can be the one who fixes the UI scaling. In the issue I shared a segment of code from R1GL that seems to reveal how the scaling is done in that case (since that implementation definitely works) and also I put in a link to the R1GL source in case you want to see more.

**Comment by mackron** [comment] 2015-10-22 08:08
I'm working on the UI scaling stuff now. Keep an eye on issue #87 for updates on that one.

**Comment by deuxsonic** [comment] 2015-10-22 08:09
Awesome, thanks.

**Comment by Yamagi** [comment] 2015-10-23 13:07
The fix was just merged.

**Closed by Yamagi** 2015-10-23 13:07 UTC

**Comment by crmb** [comment] 2015-11-10 22:37
Thanks everybody for fixing this :+1:
