### ISSUE TITLE
Select Buton Defaults to Menu instead of Start Button on controllers

### ISSUE THREAD

**Issue by OpenRift412** [yquake2/yquake2#801] opened 2022-03-19 23:28 UTC
For some reason on my Xbox controller, the select button is what opens the game menu instead of start. There doesn't seem to be any way to change this as far as I can tell.

**Comment by Yamagi** [comment] 2022-03-26 15:54
This for someone who contributed (to) the joystick code. Maybe @0lvin?

**Comment by protocultor** [comment] 2022-04-07 02:49
Hold on, this is not a bug, this is by design. Current Xbox controllers may have a "**View**" button ("Select"), but the OG Xbox and the 360 had a "**Back**" button, and these influenced the SDL button mapping of controllers. Mapping 'Back' as the '_Esc_ key' makes sense for Quake II, since the Esc key not only pulls out the menu, it also "cancels options" and "goes back" in menus.

That being said, it's nice to be able to customize the button used for menu/cancel, so I've made a pull request that does just that: https://github.com/yquake2/yquake2/pull/811

**Comment by Yamagi** [comment] 2022-04-11 07:26
I've merged the pull request.

**Closed by Yamagi** 2022-04-11 07:26 UTC
Labels: bug
