### ISSUE TITLE
7.31 pre

### ISSUE THREAD

**Issue by gribbs88** [yquake2/yquake2#356] opened 2019-01-15 03:44 UTC
Hi, The http downloading works great on maraakate's coop server, but any others that I have tried fail and there is no fall back to udp downloading like q2pro. I compiled 7.31 pre again but without http, and it works fine with udp. Just thought I'd let you all know.

**Comment by DanielGibson** [comment] 2019-01-15 03:50
Falling back to UDP is supposed to work and I think we tested that locally (in LAN)..

Can you give us a few IPs of failing servers for testing?
Thanks! :)

**Comment by gribbs88** [comment] 2019-01-15 11:12
23.227.170.222:27912
23.227.170.222:27910

Those are the two I tried - part of the tastyspleen.net group of servers. The first one is called vanilla, the second is called mutant.
Cheers,

**Comment by Yamagi** [comment] 2019-01-15 14:31
Okay. The problem is that both servers send a download URL (HTTP downloading enabled, URL: http://q2http.tastyspleen.net/) without providing the game data at that URL. That's a server side configuration error. The q2dos code had a special case for this: If too many files resulted in eror 404 it switched back to UDP downloading. I remove that because it greatly complicates and introduces other problems. I need to think about this.

**Comment by gribbs88** [comment] 2019-01-15 16:09
Thanks for looking into it. Q2pro will http download from these servers, no idea how he does it though....Maraakate's server is more important for htttp dling  because there is no other way to download the maps that I can find.Tasty has all the maps on their website anyhow.
Cheers,

**Comment by SiemensSchuckert** [comment] 2019-01-19 23:55
Tested with 23.227.170.222:27910

q2pro r1826
	GET /baseq2/maps/rene51.bsp 
	GET /baseq2.filelist 
	GET /baseq2/maps/rene51.filelist 

Yamagi Quake II v7.31pre
	GET //maps/rene51.bsp 
	GET //.filelist 
	GET //maps/rene51.filelist 

different http queries - cannot download map...

**Comment by Yamagi** [comment] 2019-01-24 17:12
I've implemented support for q2pro style URLs. The game tries r1q2 first, in case of 404 is falls back to q2pro and if everything fails to UDP. This is still in the `udpfallback` branch. A new set of Windows binaries can be found here: https://deponie.yamagi.org/quake2/misc/quake2-bd8c98.zip

There's at least one known bug. The UDP should refuse to download .bsp files from pak files. That's in sv_user.c:346. For some reason that works for mods and not for baseq2. I'm still pondering if I should fix it or remove that limitation altogether.

**Comment by gribbs88** [comment] 2019-01-26 16:34
Nice! Seems to download from both http and udp servers now without problems. Thanks!

**Comment by Yamagi** [comment] 2019-01-30 16:16
I've just merged the branch into master. Thank you all for your support!

**Closed by Yamagi** 2019-01-30 16:16 UTC

**Comment by Yamagi** [comment] 2019-01-30 16:32
And a new Windows build can be found here: https://deponie.yamagi.org/quake2/misc/quake2-29bb6e.zip
