### ISSUE TITLE
Belgian AZERTY layout has unbindable keys

### ISSUE THREAD

**Issue by InFerYes** [yquake2/yquake2#543] opened 2020-04-01 13:02 UTC
When launched in a terminal, it outputs `"<UNKNOWN KEYNUM>" isn't a valid key` when I try to bind "previous item".

In this image it is the key in red:

![https://i.imgur.com/1jbiPt5.png](https://i.imgur.com/1jbiPt5.png)

**Comment by Yamagi** [comment] 2020-04-02 15:36
This is a known limitation of Q2s input system. Most modern games use scancodes, e.g. you press the key or key combination for `ä` and the game receives the string 'ä'. With scancodes the game doesn't need any understanding of the keyboard and it's layout. But Q2 - like many old games - uses keycodes. You press `ä`, the game receives the keycode '48' for a german QWERTZ keyboard in Linux with X11. So the game needs at least a little understanding of the keyboard and it's layout, YQ2 uses SDL2 for that. Since dead keys don't generate keycodes and key combination ofzen generate codes unknown to SDL2 keys like the one you mentioned can't be bind.

The correct solution would be to switch YQ2 to scancodes, but that's a lot of work. Therefore we've never done. It might be possible to hack some fallback logic, check the scancode if an unknown keycode is received. We'll look into that but I'm afraid that it won't happen soon. :/

**Comment by InFerYes** [comment] 2020-04-02 20:13
Understandable. Can you point me in the right direction?

**Comment by Yamagi** [comment] 2020-04-03 06:41
The code is in src/client/input/sdl.c. Every keystroke ends in `IN_Update()` as `SDL_KEYUP` event. There's already a little hack using scancodes for some problems with AZERTY keyboards that I forgot about. It may be enough to enhance that. If the hack doesn't trigger the keysym is passed to `IN_TranslateSDLtoQ2Key()` which translates it to Quake IIs internal key representation. You could:

1. Alter `IN_TranslateSDLtoQ2Key()` in way that something like -1 is returned if an unknown keysym is encountered.
2. Fallback to scancodes if `IN_TranslateSDLtoQ2Key()` returns -1.

**Comment by InFerYes** [comment] 2020-04-07 21:14
`Key_KeynumToString` in src/client/cl_keyboard.c keeps returning `"<UNKNOWN KEYNUM>"` in STDOUT.

I have tried adding to `IN_TranslateSDLtoQ2Key`:

```C
case SDLK_CARET:
key = K_CARET;
```

based on https://wiki.libsdl.org/SDL_Scancode, which has the ^ character as `SDLK_CARET`, under the section 

> These virtual key values do not have corresponding physical keys

so it was a long-shot anyway.

I had added `K_CARET = 94,` to src/client/header/keyboard.h as well to match the key, which corresponds with the ASCII decimal for caret iirc.

**Comment by DanielGibson** [comment] 2020-04-08 02:48
Was thinking of a solution as implemented in #551 :)

**Comment by InFerYes** [comment] 2020-04-09 07:58
I can bind the keys now

![https://i.imgur.com/XQyT11d.png](https://i.imgur.com/XQyT11d.png)

But pressing SC_LEFTBRACKET twice drops the console.

The key that is typically the console key (on AZERTY the `²`/`³` key to the left of `1` on the top row) says "SC_GRAVE is unbound, hit F4 to set."

**Comment by DanielGibson** [comment] 2020-04-09 20:28
That'll be due to this: https://github.com/yquake2/yquake2/blob/master/src/client/cl_keyboard.c#L1056

I'm not sure if we can change this in a way that doesn't piss off too many people (that are used to opening the console with one of those keycodes, which are on that "classic console key" (SC_GRAVE) on some common layouts)..
We introduced Shift+Escape for opening the console a while ago, but I guess many people still prefer to use the "console key".

I'll have to think about this a bit more, there might be a solution that works better than the current hack.

**Comment by DanielGibson** [comment] 2020-04-10 00:40
I just added a workaround for the console key problem to the merge request, can you test it? :)

**Comment by InFerYes** [comment] 2020-04-10 07:24
The console properly drops with `²`/`³` but every time I **close** the console `<UNKNOWN KEYNUM> is unbound, hit F4 to set.` gets printed to the console. It doesn't get printed when I open the console.

The "grave" is aka a "backtick". I've been looking up some keyboard layouts and I noticed that indeed some layouts have a backtick in place of the tilde, but AZERTY BE has neither, but rather the "uppercase 2 and 3" (square and cube). Just putting this out for future reference should anyone come across this problem, know that you can bind/use the keys, they just have a different name ingame.

**Comment by InFerYes** [comment] 2020-04-10 07:26
Opening the console with `²`/`³` and closing with shift-ESC does not print `<UNKNOWN KEYNUM> is unbound, hit F4 to set.`.

Opening the console with shift-ESC and closing with `²`/`³` does print `<UNKNOWN KEYNUM> is unbound, hit F4 to set.`.

**Comment by DanielGibson** [comment] 2020-04-10 14:46
I just pushed a fix, can you test it?
I don't get that unbound key message so I couldn't test it myself

**Comment by InFerYes** [comment] 2020-04-10 19:46
No perceivable changes. Still prints `<UNKNOWN KEYNUM> is unbound, hit F4 to set.` same as my last comment.

**Comment by DanielGibson** [comment] 2020-04-11 01:06
I tried all the Belgian layouts XFCE's keyboard settings let me configure and I still couldn't reproduce the problem..
I just force-push a tiny change to the last commit, can you try again?

**Comment by InFerYes** [comment] 2020-04-11 17:38
I have checked if i have the last PR on the scancode branch:

![https://i.imgur.com/DO0snzf.png](https://i.imgur.com/DO0snzf.png)

But when I launch the game now I get

```X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  106
  Current serial number in output stream:  107
1 user@ranger ~/AUR_builds/yamagi-quake2 %                                                                                                                                                                                                                                                                             :(
```

build output for reference:
```
[96/226] Building C object CMakeFiles/q2ded.dir/src/common/unzip/miniz.c.o
/home/user/AUR_builds/yamagi-quake2/src/quake2-7.42/src/common/unzip/miniz.c:3030:9: note: #pragma message: Using fopen, ftello, fseeko, stat() etc. path for file I/O - this path may not support large files.
 3030 | #pragma message("Using fopen, ftello, fseeko, stat() etc. path for file I/O - this path may not support large files.")
      |         ^~~~~~~
[140/226] Building C object CMakeFiles/quake2.dir/src/client/cl_keyboard.c.o
In function ‘Key_Console’,
    inlined from ‘Key_Console’ at /home/user/AUR_builds/yamagi-quake2/src/quake2-7.42/src/client/cl_keyboard.c:334:1:
/home/user/AUR_builds/yamagi-quake2/src/quake2-7.42/src/client/cl_keyboard.c:472:4: warning: ‘__builtin_stpcpy’ accessing 1 byte at offsets [0, 32768] and [0, 31744] may overlap 1 byte at offset 0 [-Wrestrict]
  472 |    strcpy(key_lines[edit_line], key_lines[history_line]);
      |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/user/AUR_builds/yamagi-quake2/src/quake2-7.42/src/client/cl_keyboard.c:445:3: warning: ‘__builtin_stpcpy’ accessing 1 byte at offsets [0, 32768] and [0, 31744] may overlap 1 byte at offset 0 [-Wrestrict]
  445 |   strcpy(key_lines[edit_line], key_lines[history_line]);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/user/AUR_builds/yamagi-quake2/src/quake2-7.42/src/client/cl_keyboard.c:548:3: warning: ‘memmove’ offset [-2147483647, -1] is out of the bounds [0, 32768] of object ‘key_lines’ with type ‘char[32][1024]’ [-Warray-bounds]
  548 |   memmove(key_lines[edit_line] + key_linepos + 1,
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  549 |     key_lines[edit_line] + key_linepos,
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  550 |     length - key_linepos);
      |     ~~~~~~~~~~~~~~~~~~~~~
/home/user/AUR_builds/yamagi-quake2/src/quake2-7.42/src/client/cl_keyboard.c: In function ‘Key_Console’:
/home/user/AUR_builds/yamagi-quake2/src/quake2-7.42/src/client/cl_keyboard.c:38:6: note: ‘key_lines’ declared here
   38 | char key_lines[NUM_KEY_LINES][MAXCMDLINE];
      |      ^~~~~~~~~
[183/226] Building C object CMakeFiles/quake2.dir/src/client/sound/ogg.c.o
In file included from /home/user/AUR_builds/yamagi-quake2/src/quake2-7.42/src/client/sound/ogg.c:41:
/home/user/AUR_builds/yamagi-quake2/src/quake2-7.42/src/client/sound/header/stb_vorbis.h: In function ‘decode_residue’:
/home/user/AUR_builds/yamagi-quake2/src/quake2-7.42/src/client/sound/header/stb_vorbis.h:891:41: warning: statement with no effect [-Wunused-value]
  891 | #define temp_free(f,p)                  0
      |                                         ^
/home/user/AUR_builds/yamagi-quake2/src/quake2-7.42/src/client/sound/header/stb_vorbis.h:2268:4: note: in expansion of macro ‘temp_free’
 2268 |    temp_free(f,part_classdata);
      |    ^~~~~~~~~
/home/user/AUR_builds/yamagi-quake2/src/quake2-7.42/src/client/sound/header/stb_vorbis.h: In function ‘inverse_mdct’:
/home/user/AUR_builds/yamagi-quake2/src/quake2-7.42/src/client/sound/header/stb_vorbis.h:891:41: warning: statement with no effect [-Wunused-value]
  891 | #define temp_free(f,p)                  0
      |                                         ^
/home/user/AUR_builds/yamagi-quake2/src/quake2-7.42/src/client/sound/header/stb_vorbis.h:2917:4: note: in expansion of macro ‘temp_free’
 2917 |    temp_free(f,buf2);
      |    ^~~~~~~~~
In file included from /home/user/AUR_builds/yamagi-quake2/src/quake2-7.42/src/client/sound/ogg.c:41:
/home/user/AUR_builds/yamagi-quake2/src/quake2-7.42/src/client/sound/header/stb_vorbis.h: In function ‘start_decoder.part.0’:
/home/user/AUR_builds/yamagi-quake2/src/quake2-7.42/src/client/sound/header/stb_vorbis.h:3953:32: warning: ‘hi’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 3953 |             g->neighbors[j][1] = hi;
      |             ~~~~~~~~~~~~~~~~~~~^~~~
/home/user/AUR_builds/yamagi-quake2/src/quake2-7.42/src/client/sound/header/stb_vorbis.h:3952:32: warning: ‘low’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 3952 |             g->neighbors[j][0] = low;
      |             ~~~~~~~~~~~~~~~~~~~^~~~~
/home/user/AUR_builds/yamagi-quake2/src/quake2-7.42/src/client/sound/header/stb_vorbis.h: In function ‘stb_vorbis_seek_frame’:
/home/user/AUR_builds/yamagi-quake2/src/quake2-7.42/src/client/sound/header/stb_vorbis.h:4682:23: warning: ‘offset’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 4682 |                offset += error * 2;
      |                ~~~~~~~^~~~~~~~~~~~
/home/user/AUR_builds/yamagi-quake2/src/quake2-7.42/src/client/sound/header/stb_vorbis.h:4629:11: note: ‘offset’ was declared here
 4629 |    double offset, bytes_per_sample;
      |           ^~~~~~
/home/user/AUR_builds/yamagi-quake2/src/quake2-7.42/src/client/sound/header/stb_vorbis.h:4679:23: warning: ‘bytes_per_sample’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 4679 |                double error = ((double) sample_number - mid.last_decoded_sample) * bytes_per_sample;
      |                       ^~~~~
/home/user/AUR_builds/yamagi-quake2/src/quake2-7.42/src/client/sound/header/stb_vorbis.h:4629:19: note: ‘bytes_per_sample’ was declared here
 4629 |    double offset, bytes_per_sample;
      |                   ^~~~~~~~~~~~~~~~
[223/226] Building C object CMakeFiles/quake2.dir/src/common/unzip/miniz.c.o
/home/user/AUR_builds/yamagi-quake2/src/quake2-7.42/src/common/unzip/miniz.c:3030:9: note: #pragma message: Using fopen, ftello, fseeko, stat() etc. path for file I/O - this path may not support large files.
 3030 | #pragma message("Using fopen, ftello, fseeko, stat() etc. path for file I/O - this path may not support large files.")
      |         ^~~~~~~
[226/226] Linking C shared module release/ref_gl1.so
```

**Comment by DanielGibson** [comment] 2020-04-11 17:45
I'm very sure I didn't do any change that could cause that problem :)

Have you tried rebooting? I think I got that error if the kernel and/or GPU driver has been updated without rebooting afterwards.
If it persists after reboot, make sure everything is properly updated, like maybe some packages of the nvidia(?) driver are still at the old version or sth (do other 3D games work?)

**Comment by InFerYes** [comment] 2020-04-11 18:19
A reboot indeed fixed it. I will remove that last comment to avoid future confusion.

**Comment by InFerYes** [comment] 2020-04-11 20:26
I have found 1 issue. When I bind `^` and `$` (qwerty equiv: `[` and `]`) to prev item and next item via the menu, it will not save `$` when I quit the client. When I use `DOWNARROW` and quit, it does save.

**Comment by DanielGibson** [comment] 2020-04-11 21:20
I'll take a look, maybe $ is somehow handled in a special way when writing or reading configs

**Comment by DanielGibson** [comment] 2020-04-11 22:42
Turns out, $ can be used in macros and will be replaced with the value of the corresponding cvar?!

Like `/alias tellrenderer "I'm using the $vid_renderer renderer"`
and then running `/tellrenderer` in the console will output something like
`Player: I'm using the gl3 renderer`
Wild!

Anyway, I pushed a fix for this to #551, please test again :)

**Comment by InFerYes** [comment] 2020-04-12 19:08
Instead of `$` it now says `DOLLAR` as the key. The bind also persists.

**Comment by DanielGibson** [comment] 2020-04-12 19:52
It is generally necessary in Quake2, because if the config parser encounters $ it thinks that a variable is following and tries to replace $ (and the following characters, if any) with the value of the variable (like "gl3" in the example above).
As far as I know Quake2 has always done this.
But original Quake2 pretended that all keyboards have US-QWERTY layout, so it didn't run into the problem of keybindings with the `$` key (you get a "$" by pressing shift+4 there).

Only Yamagi Quake II does this substitution (once #551 is merged), as far as I know, though I assume that other source ports (that more or less respect the systems keyboard layout) have the same problem.

**Closed** 2020-04-20 06:59 UTC
