### ISSUE TITLE
Mouse precision greatly reduced with sensitivity setting lower than 1

### ISSUE THREAD

**Issue by 77Mynameislol77** [yquake2/yquake2#419] opened 2019-07-05 14:21 UTC
Something akin to this.

[https://www.youtube.com/watch?v=j70LaREi4e8](url)

This is a problem for high-dpi/low-sensitivity players, any idea what might be causing this?

Try it by testing the command "sensitivity 0.99" against "sensitivity 1"

**Comment by Yamagi** [comment] 2019-07-11 11:53
This *might* be caused by https://github.com/yquake2/yquake2/blob/master/src/client/input/sdl.c#L743 Fixing this without breaking existing config (by changing the sensitivity scale, for example) won't be easy and will take a few days.

**Comment by Yamagi** [comment] 2019-07-20 14:22
I just pushed an possible fix into the `sensitivity` branch: https://github.com/yquake2/yquake2/tree/sensitivity I'll build a new set of Windows binaries tomorrow.

**Comment by Yamagi** [comment] 2019-07-21 14:57
The binaries can be found here: https://deponie.yamagi.org/quake2/misc/quake2-20190721-eaa4aa.zip

**Comment by 77Mynameislol77** [comment] 2019-07-21 15:52
Yes, Works great!

**Comment by Yamagi** [comment] 2019-07-31 11:36
I've merged it into master, the fix will be part of the next release.

**Closed** 2019-07-31 11:36 UTC

**Comment by 77Mynameislol77** [comment] 2019-11-20 23:24
Alright, i just have to say it. You've managed to create the best mouse input EVER.

I have played competitive games like Counter-Strike, Quake III, Quake Live, Six Siege ect ect. But none has ever gotten the mouse input perfect.

You have! and it is SO smooth, that for the first time ever, i can feel that that it's the WEIGHT of my gaming mouse that's slowing me down, not my monitor, or the game. 

Ever since you uploaded the binaries, this source port has been the basis for how i compare the input lag between games, and i fear that no game or even source port for that matter, will ever get to have as great mouse input as this source port has.

You've succeeded where even the AAA industry have failed. You've managed to create the PERFECT mouse input. No input lag. No smoothing. Pure Perfection.

I just really felt like i needed to write this. It's THAT perfect.

**Comment by DanielGibson** [comment] 2019-11-25 21:37
Thanks for the feedback, we're glad you like it!

It's nice to get positive feedback instead of just bugreports =)
